AppRover: FeatureOption Class Reference
FeatureOption Class Reference
Class for managing a specific optional feature for a package (like USE flags in Gentoo's portage).
#include <FeatureOption.h>
Public Member Functions
FeatureOption (const FeatureOption *clone)
bool Save (xmlNodePtr parentNode) const
bool Load (xmlNodePtr featureNode)
string GetName () const
void SetName (string name)
bool IsEnabled () const
void Enable ()
void Disable ()
Private Attributes
string mName
The name of this optional feature.
bool mEnabled
The state of whether this feature should be used by a package.
Detailed Description
Class for managing a specific optional feature for a package (like USE flags in Gentoo's portage).
Constructor & Destructor Documentation
FeatureOption::FeatureOption (const FeatureOption * clone)
Parameters:
clone - the optional feature to copy
References mEnabled, and mName.
Member Function Documentation
void FeatureOption::Disable ()
Sets the state of this feature to disabled
References mEnabled.
Referenced by AppRover::Install().
void FeatureOption::Enable ()
Sets the state of this feature to enabled
References mEnabled.
Referenced by AppRover::Install().
string FeatureOption::GetName () const
Returns:
the name of this optional feature
References mName.
Referenced by AppRover::Install().
bool FeatureOption::IsEnabled () const
Returns:
true if this feature is enabled
References mEnabled.
bool FeatureOption::Load (xmlNodePtr featureNode)
Parameters:
featureNode - the XML DOM node containing date for this feature
Returns:
false if featureNode is null or does not contain a feature name
References mEnabled, and mName.
Referenced by Package::Load(), and InstallEntry::Load().
bool FeatureOption::Save (xmlNodePtr parentNode) const
Parameters:
parentNode - the XML DOM node which will be the parent to the node for this feature
Returns:
false if parentNode is NULL
References mEnabled, and mName.
void FeatureOption::SetName (string name)
Parameters:
name - the new name for this optional feature
References mName.
The documentation for this class was generated from the following files:
FeatureOption.h
FeatureOption.cpp