AppRover: Package Class Reference
Package Class Reference
Class for handling all relevant data pertaining to a particular revision of an application.
#include <Package.h>
Public Member Functions
Package (const Package *refPackage, string revision)
bool Save ()
bool Save (string filename)
bool Load (string filename)
bool IsNewerThan (const Package *refPackage) const
string GetName () const
void SetName (string packageName)
const Revision & GetRevision () const
void SetRevision (string revision)
string GetSlot () const
void SetSlot (string slot)
int GetBinaryCompatabilityRevision () const
void SetBinaryCompatabilityRevision (int revision)
int GetNumSourceFiles () const
SourceFile * GetSourceFile (int fileNumber)
bool AddSourceFile (SourceFile *file)
bool RemoveSourceFile (int fileNumber)
void ClearSourceFiles ()
bool RecordSourceChecksums (string storageDirectory)
void AddUnpackInstruction (string instruction)
bool DumpUnpackInstructionsToFile (FILE *file) const
void ClearUnpackInstructions ()
void AddConfigureInstruction (string instruction)
bool DumpConfigureInstructionsToFile (FILE *file) const
void ClearConfigureInstructions ()
void AddBuildInstruction (string instruction)
bool DumpBuildInstructionsToFile (FILE *file) const
void ClearBuildInstructions ()
void AddInstallInstruction (string instruction)
bool DumpInstallInstructionsToFile (FILE *file) const
void ClearInstallInstructions ()
void AddUninstallInstruction (string instruction)
bool DumpUninstallInstructionsToFile (FILE *file) const
void ClearUninstallInstructions ()
int GetNumDependencies () const
const PackageDependency * GetDependency (int dependencyNumber) const
void AddDependency (PackageDependency *dependency)
bool RemoveDependency (string packageName)
void ClearDependencies ()
int GetNumFeatures () const
FeatureOption * GetFeature (int featureNumber) const
void AddFeature (FeatureOption *feature)
bool RemoveFeature (string featureName)
void ClearFeatures ()
bool Fetch (InstallEntry *logEntry, string storageDirectory, bool force=false) const
bool Unpack (InstallEntry *logEntry, string storageDirectory, string workDirectory, int numProcessors)
bool Configure (InstallEntry *logEntry, string workDirectory, int numProcessors)
bool Build (InstallEntry *logEntry, string workDirectory, int numProcessors)
bool Install (InstallEntry *logEntry, string workDirectory, int numProcessors)
Private Attributes
string mFilename
The of the file which contains this package data.
PackageDependencyVector mDependencies
List of required dependencies for intalling this package.
FeatureOptionVector mFeatures
List of optional features and their default states which can be used by this package.
string mPackageName
The name of the application.
Revision mPackageRevision
The revision of the application and this package.
string mPackageSlot
The slot which is occupies by this package.
int mBinaryCompatabilityRevision
Value used to indiciate if two packages have binary compatable interfaces.
SourceFileVector mSourceFiles
List of files required to install this package.
vector< string > mInstalledFiles
List of installed files to be used for detecting if this package has been installed.
vector< string > mInstalledDirectories
List of installed directories to be used for detecting if this package has been installed.
InstructionSequence mUnpackInstructions
The instructions to unpack this package.
InstructionSequence mConfigureInstructions
The instructions to configure this package.
InstructionSequence mBuildInstructions
The instructions to build this package.
InstructionSequence mInstallInstructions
The instructions to install this package.
InstructionSequence mUninstallInstructions
The instructions to uninstall this package.
Detailed Description
Class for handling all relevant data pertaining to a particular revision of an application.
Constructor & Destructor Documentation
Package::Package (const Package * refPackage, string revision)
Parameters:
refPackage - package used as a base
revision - the revision for this package
Creates a new package which is an updated copy of refPackage. The new package is the same as refPackage except that all references to refPackage's revision is changed to the new packages revision.
References PackageDependency::GetMaxRevision(), PackageDependency::GetMinRevision(), Revision::GetString(), mBinaryCompatabilityRevision, mBuildInstructions, mConfigureInstructions, mDependencies, mFeatures, mFilename, mInstallInstructions, mPackageName, mPackageRevision, mPackageSlot, mSourceFiles, mUninstallInstructions, mUnpackInstructions, InstructionSequence::ReplaceString(), Revision::Set(), and SourceFile::SetCondition().
Member Function Documentation
void Package::AddBuildInstruction (string instruction)
Parameters:
instruction - the new instruction
Adds an instruction to the end of the list of build instructions.
References InstructionSequence::AddInstruction(), and mBuildInstructions.
Referenced by PackageWizard::next().
void Package::AddConfigureInstruction (string instruction)
Parameters:
instruction - the new instruction
Adds an instruction to the end of the list of configuration instructions.
References InstructionSequence::AddInstruction(), and mConfigureInstructions.
Referenced by PackageWizard::next().
void Package::AddDependency (PackageDependency * dependency)
Parameters:
dependency - the dependency to add
Adds a dependency to the list of dependencies.
References mDependencies.
Referenced by PackageWizard::next().
void Package::AddFeature (FeatureOption * feature)
Parameters:
feature - optional feature to be added to the list
References mFeatures.
void Package::AddInstallInstruction (string instruction)
Parameters:
instruction - the new instruction
Adds an instruction to the end of the list of install instructions.
References InstructionSequence::AddInstruction(), and mInstallInstructions.
Referenced by PackageWizard::next().
bool Package::AddSourceFile (SourceFile * file)
Parameters:
file - the source file to add
Returns:
false if file is NULL
Adds file to the end of the list of source files. "Source" indicates a file to be fetched and does not necessarily indicate that it contains source code.
References mSourceFiles.
Referenced by PackageWizard::next().
void Package::AddUninstallInstruction (string instruction)
instruction - the new instruction
Adds an instruction to the end of the list of uninstall instructions.
References InstructionSequence::AddInstruction(), and mUninstallInstructions.
Referenced by PackageWizard::accept().
void Package::AddUnpackInstruction (string instruction)
Parameters:
instruction - the new instruction
Adds an instruction to the end of the list of unpacking instructions.
References InstructionSequence::AddInstruction(), and mUnpackInstructions.
Referenced by PackageWizard::next().
bool Package::Build (InstallEntry * logEntry, string workDirectory, int numProcessors)
Parameters:
logEntry - the install log entry corresponding to this package
workDirectory - the parent directory of all package working directories
numProcessors - number of processors in system (for parallelization)
Returns:
false if logEntry is NULL or an error occurs while building
Builds the package by executing all build instructions from the working directory.
References InstructionSequence::Execute(), Revision::GetString(), Interpreter::Interpret(), mBuildInstructions, mPackageName, mPackageRevision, InstallEntry::SetBuilt(), InstallEntry::SetErrorMessage(), and InstructionSequence::SetStartingDirectory().
Referenced by AppRover::BuildPackage().
void Package::ClearBuildInstructions ()
Deletes all of the build instructions.
References InstructionSequence::Clear(), and mBuildInstructions.
Referenced by PackageWizard::back(), and PackageWizard::next().
void Package::ClearConfigureInstructions ()
Deletes all of the configuration instructions.
References InstructionSequence::Clear(), and mConfigureInstructions.
Referenced by PackageWizard::back(), and PackageWizard::next().
void Package::ClearDependencies ()
Empties the list of dependencies files.
References mDependencies.
Referenced by PackageWizard::back(), and PackageWizard::next().
void Package::ClearFeatures ()
Removes all entries from the list of optional features
References mFeatures.
void Package::ClearInstallInstructions ()
Deletes all of the install instructions.
References InstructionSequence::Clear(), and mInstallInstructions.
Referenced by PackageWizard::back(), and PackageWizard::next().
void Package::ClearSourceFiles ()
Empties the list of source files.
References mSourceFiles.
Referenced by PackageWizard::back(), and PackageWizard::next().
void Package::ClearUninstallInstructions ()
Deletes all of the uninstall instructions.
References InstructionSequence::Clear(), and mUninstallInstructions.
Referenced by PackageWizard::accept(), and PackageWizard::back().
void Package::ClearUnpackInstructions ()
Deletes all of the unpacking instructions.
References InstructionSequence::Clear(), and mUnpackInstructions.
Referenced by PackageWizard::back(), and PackageWizard::next().
bool Package::Configure (InstallEntry * logEntry, string workDirectory, int numProcessors)
Parameters:
logEntry - the install log entry corresponding to this package
workDirectory - the parent directory of all package working directories
numProcessors - number of processors in system (for parallelization)
Returns:
false if logEntry is NULL or an error occurs while configuring
Configures the package by executing all configure instructions from the working directory.
References InstructionSequence::Execute(), Revision::GetString(), Interpreter::Interpret(), mConfigureInstructions, mPackageName, mPackageRevision, InstallEntry::SetConfigured(), InstallEntry::SetErrorMessage(), and InstructionSequence::SetStartingDirectory().
Referenced by AppRover::ConfigurePackage().
bool Package::DumpBuildInstructionsToFile (FILE * file) const
Parameters:
file - the file to receive the build instructions
Returns:
true if the build instructions were successfully saved to the file
References InstructionSequence::DumpToFile(), and mBuildInstructions.
bool Package::DumpConfigureInstructionsToFile (FILE * file) const
Parameters:
file - the file to receive the configuration instructions
Returns:
true if the configuration instructions were successfully saved to the file
References InstructionSequence::DumpToFile(), and mConfigureInstructions.
bool Package::DumpInstallInstructionsToFile (FILE * file) const
Parameters:
file - the file to receive the install instructions
Returns:
true if the install instructions were successfully saved to the file
References InstructionSequence::DumpToFile(), and mInstallInstructions.
bool Package::DumpUninstallInstructionsToFile (FILE * file) const
Parameters:
file - the file to receive the uninstall instructions
Returns:
true if the uninstall instructions were successfully saved to the file
References InstructionSequence::DumpToFile(), and mUninstallInstructions.
bool Package::DumpUnpackInstructionsToFile (FILE * file) const
Parameters:
file - the file to receive the unpacking instructions
Returns:
true if the unpacking instructions were successfully saved to the file
References InstructionSequence::DumpToFile(), and mUnpackInstructions.
bool Package::Fetch (InstallEntry * logEntry, string storageDirectory, bool force = false) const
Parameters:
logEntry - the install log entry corresponding to this package
storageDirectory - the directory where source files are stored
force (=false) - if true, fetch all files even if local copies exist
Returns:
false if logEntry is NULL or a file cannot be retrieved
This retrieves all files needed in order to install the package.
References Fetcher::Fetch(), InstallEntry::GetFeatures(), Revision::GetString(), mPackageName, mPackageRevision, mSourceFiles, and InstallEntry::SetErrorMessage().
Referenced by AppRover::FetchPackage().
int Package::GetBinaryCompatabilityRevision () const
Returns:
the value used to indicate if 2 packages have binary compatable interfaces
References mBinaryCompatabilityRevision.
Referenced by AppRover::Install().
const PackageDependency * Package::GetDependency (int dependencyNumber) const
Parameters:
dependencyNumber - the index to the dependency list
Returns:
NULL if the index is invalid
Otherwise, a pointer to the dependency object
References mDependencies.
Referenced by AppRover::Install().
FeatureOption * Package::GetFeature (int featureNumber) const
Parameters:
featureNumber - the index into the list of optional features
Returns:
the feature at the specified location in the list
NULL if featureNumber is invalid
References mFeatures.
Referenced by AppRover::Install().
string Package::GetName () const
Returns:
the name of this package
References mPackageName.
Referenced by Repository::AddPackage(), PackageIndex::AddPackage(), AppRover::Install(), PackageDependency::IsSatisfiedBy(), RemoveDependency(), RemoveFeature(), PackageWizard::RevisionChanged(), and PackageWizard::showPage().
int Package::GetNumDependencies () const
Returns:
the number of prerequisite packages that must be satisfied before this package can be installed
References mDependencies.
Referenced by AppRover::Install().
int Package::GetNumFeatures () const
Returns:
the number of optional features recognized by this package
References mFeatures.
Referenced by AppRover::Install().
int Package::GetNumSourceFiles () const
Returns:
the number of files required to install this package
References mSourceFiles.
const Revision & Package::GetRevision () const
Returns:
the revision of this package
References mPackageRevision.
Referenced by Repository::AddPackage(), PackageIndex::AddPackage(), AppRover::Install(), PackageDependency::IsSatisfiedBy(), PackageWizard::NameChanged(), PackageWizard::showPage(), and AppRover::Update().
string Package::GetSlot () const
Returns:
the slot this package occupies
References mPackageSlot.
Referenced by AppRover::Install().
SourceFile * Package::GetSourceFile (int fileNumber)
Parameters:
fileNumber - index into the list of source files
Returns:
the source file at the specifed position in the list
NULL if fileNumber is invalid
References mSourceFiles.
bool Package::Install (InstallEntry * logEntry, string workDirectory, int numProcessors)
Parameters:
logEntry - the install log entry corresponding to this package
workDirectory - the parent directory of all package working directories
numProcessors - number of processors in system (for parallelization)
Returns:
false if logEntry is NULL or an error occurs while installing
Installs the package by executing all install instructions from the working directory.
References InstallEntry::AddInstalledDirectory(), InstallEntry::AddInstalledFile(), InstallEntry::AddInstalledSymLink(), InstallEntry::ConsolidateFiles(), InstructionSequence::Execute(), InstructionSequence::GetStartingDirectory(), Revision::GetString(), Interpreter::Interpret(), mInstallInstructions, mPackageName, mPackageRevision, mUninstallInstructions, InstallEntry::SetErrorMessage(), InstallEntry::SetInstalled(), InstructionSequence::SetStartingDirectory(), and InstallEntry::SetUninstallInstructions().
Referenced by AppRover::InstallPackage().
bool Package::IsNewerThan (const Package * refPackage) const
Parameters:
refPackage - the package to compare against
Returns:
true if this package has a higher revision number than refPackage
Compares the revision numbers of this package with refPackage and returns true if this package has a higher revision number.
References mPackageRevision.
Referenced by AppRover::FindMostCurrentPackage().
bool Package::Load (string filename)
Parameters:
filename - the file containing the package data
Returns:
false if filename is "", the file doesn't exists, or there is a format error in the file
Loads the package data from the specified file.
References InstructionSequence::Load(), SourceFile::Load(), FeatureOption::Load(), PackageDependency::Load(), mBinaryCompatabilityRevision, mBuildInstructions, mConfigureInstructions, mDependencies, mFeatures, mFilename, mInstalledDirectories, mInstalledFiles, mInstallInstructions, mPackageName, mPackageRevision, mPackageSlot, mSourceFiles, mUninstallInstructions, mUnpackInstructions, and Revision::Set().
Referenced by PackageIndex::GetMostCurrentPackage(), and PackageIndex::GetPrecedingPackage().
bool Package::RecordSourceChecksums (string storageDirectory)
Parameters:
storageDirectory - location where local copies of source files are stored
Returns:
true if checksums were successfully calculated for all source files
References Fetcher::Fetch(), Fetcher::GetChecksum(), and mSourceFiles.
Referenced by AppRover::AddNewPackage(), and AppRover::UpdatePackageChecksums().
bool Package::RemoveDependency (string packageName)
Parameters:
packageName - the name of package to be removed from the list of dependencies
Returns:
false if packageName is "" or is not a dependency of this package
References GetName(), and mDependencies.
bool Package::RemoveFeature (string featureName)
Parameters:
featureName - name of the optional feature to be removed from the list
Returns:
false if featureName is "" or does not match any features in the list
References GetName(), and mFeatures.
bool Package::RemoveSourceFile (int fileNumber)
Parameters:
fileNumber - index into the list of source files
Returns:
false if fileNumber is invalid
References mSourceFiles.
bool Package::Save ()
Returns:
true if this package was successfully saved to the file specified by mFilename
References mFilename.
Referenced by Save().
bool Package::Save (string filename)
Parameters:
filename - the file to receive the package data
Returns:
false if filename is "" or is not writable
Saves the package data to the specified file.
References Revision::GetString(), mBinaryCompatabilityRevision, mBuildInstructions, mConfigureInstructions, mDependencies, mFeatures, mFilename, mInstalledDirectories, mInstalledFiles, mInstallInstructions, mPackageName, mPackageRevision, mPackageSlot, mSourceFiles, mUninstallInstructions, mUnpackInstructions, InstructionSequence::Save(), and Save().
void Package::SetBinaryCompatabilityRevision (int revision)
Parameters:
revision - the value used to indicate if 2 packages have binary compatable interfaces
References mBinaryCompatabilityRevision.
void Package::SetName (string packageName)
Parameters:
packageName - the new name of this package
Sets the name of this package to the specified string.
References mPackageName.
Referenced by PackageWizard::NameChanged().
void Package::SetRevision (string revision)
Parameters:
revision - the new revision of this package
Sets the revision of this package to the specified value.
References mPackageRevision, and Revision::Set().
Referenced by PackageWizard::RevisionChanged().
void Package::SetSlot (string slot)
Parameters:
slot - the slot this package occupies
References mPackageSlot.
bool Package::Unpack (InstallEntry * logEntry, string storageDirectory, string workDirectory, int numProcessors)
Parameters:
logEntry - the install log entry corresponding to this package
storageDirectory - the directory where source files are stored
workDirectory - the parent directory of all package working directories
numProcessors - number of processors in system (for parallelization)
Returns:
false if logEntry is NULL or an error occurs while unpacking
Unpacks the package by creating a working directory and copying all source files to the working directory. If any unpacking instructions have been specified, they will then be executed from the working directory.
References InstructionSequence::Execute(), InstallEntry::GetFeatures(), Revision::GetString(), Interpreter::Interpret(), mPackageName, mPackageRevision, mSourceFiles, mUnpackInstructions, InstallEntry::SetErrorMessage(), InstructionSequence::SetStartingDirectory(), and InstallEntry::SetUnpacked().
Referenced by AppRover::UnpackPackage().
The documentation for this class was generated from the following files:
Package.h
Package.cpp