AppRover: BooleanExpression Class Reference
BooleanExpression Class Reference
Class for evaluating the value of a boolean expression.
#include <BooleanExpression.h>
Public Member Functions
string GetString () const
bool ParseFromString (string expression)
bool IsEmpty () const
bool EvaluatesToTrue (const FeatureOptionVector &features) const
BooleanExpression & operator= (const BooleanExpression &src)
Private Member Functions
bool GetFeatureValue (const FeatureOptionVector &features, string feature) const
bool ParseString (string expression, bool isTopLevel)
string PopArgument (string &arguments) const
Private Attributes
vector< string > mArgumentsInReversePolishNotation
the operands and operators of the experession listed in reverse polish notation
string mDisplayString
the expression shown in "normal" notation
Detailed Description
Class for evaluating the value of a boolean expression.
Member Function Documentation
bool BooleanExpression::EvaluatesToTrue (const FeatureOptionVector & features) const
Parameters:
features - the list of optional feature states used to evaluate the value of the expression
Returns:
true if the expression evaluates to true
false if the expression evaluates to false or is empty
References GetFeatureValue(), and mArgumentsInReversePolishNotation.
Referenced by InstructionSequence::ConditionFulfilled(), SourceFile::IsActive(), and PackageDependency::IsActive().
bool BooleanExpression::GetFeatureValue (const FeatureOptionVector & features, string feature) const [private]
Parameters:
features - the list of optional feature states used to evaluate this expression
feature - the name of an optional feature whose state is desired
Returns:
true if the feature is found in the list and is enabled
Todo:
Decide how to handle this case. Perhaps I will exit
Referenced by EvaluatesToTrue().
string BooleanExpression::GetString () const
Returns:
string containing the expression in "normal" notation
References mDisplayString.
Referenced by PackageDependency::GetDependentString(), PackageDependency::GetString(), SourceFile::Save(), and PackageDependency::Save().
bool BooleanExpression::IsEmpty () const
Returns:
true if the expression does not contain any elements
References mDisplayString.
Referenced by SourceFile::IsActive(), and PackageDependency::IsActive().
BooleanExpression & BooleanExpression::operator= (const BooleanExpression & src)
Parameters:
src - the boolean expression to copy
Returns:
reference to this boolean expression
References mArgumentsInReversePolishNotation, and mDisplayString.
bool BooleanExpression::ParseFromString (string expression)
Parameters:
expression - a new boolean expression in "normal" notation
Returns:
true if the expression could be properly parsed
Clears the current contents of the expression. If the new expression can be parsed, it will be used, otherwise the expression is left empty.
References mArgumentsInReversePolishNotation, mDisplayString, and ParseString().
Referenced by InstructionSequence::ConditionFulfilled(), SourceFile::Load(), and PackageDependency::Load().
bool BooleanExpression::ParseString (string expression, bool isTopLevel) [private]
Parameters:
expression - the remaining portion of an expression to be parsed
isTopLevel - if true, indiciates that we are working with the entire boolean expression
Returns:
true if the relevant portion of the expression could be successfully parsed
This function recursively parses an expression. The top level call fails if any characters are left unparsed.
References mArgumentsInReversePolishNotation, and PopArgument().
Referenced by ParseFromString().
string BooleanExpression::PopArgument (string & arguments) const [private]
Parameters:
arguments - string of tokens separated by whitespace
Returns:
string containing the next token ("" if there are no token remaining)
Modifies the input arguments to remove the leading token from the string and returns the token.
Referenced by ParseString().
The documentation for this class was generated from the following files:
BooleanExpression.h
BooleanExpression.cpp