AppRover: PackageWizard Class Reference
PackageWizard Class Reference
Wizard class used to create and edit packages within the KDE AppRover GUI.
#include <kPackageWizard.h>
Public Slots
void NameChanged (const QString &newName)
void RevisionChanged (const QString &newName)
void AddDependency ()
void RemoveDependency ()
void AddFile ()
void RemoveFile ()
void InstallChanged ()
void UninstallChanged ()
Public Member Functions
PackageWizard (Package *package, QWidget *parent=NULL, const char *name=NULL)
void showPage (QWidget *page)
Protected Slots
virtual void next ()
virtual void back ()
virtual void accept ()
Private Attributes
QVBox * mNamePage
Wizard page for editing things like name and revision.
QVBox * mDependencyPage
Wizard page for editing package dependencies.
QVBox * mFilePage
Wizard page for editing source files.
QVBox * mUnpackPage
Wizard page for setting unpacking instructions.
QVBox * mConfigurePage
Wizard page for setting configuration instructions.
QVBox * mBuildPage
Wizard page for setting build instructions.
QVBox * mInstallPage
Wizard page for setting install instructions.
QVBox * mUninstallPage
Wizard page for setting uninstall instructions.
KLineEdit * mNameEdit
Edit box for package name.
KLineEdit * mFileEdit
Edit box for entering a new source file.
KListView * mFileList
List view of all source files.
KLineEdit * mDependencyNameEdit
Edit box for entering dependency name.
KLineEdit * mDependencyRevisionEdit
Edit box for entering dependency revision.
KListView * mDependencyList
List view of all package dependencies.
QTextEdit * mUnpackInstructions
Edit box for unpacking instructions.
QTextEdit * mConfigureInstructions
Edit box for configuration instructions.
QTextEdit * mBuildInstructions
Edit box for build instructions.
QTextEdit * mInstallInstructions
Edit box for install instructions.
QTextEdit * mUninstallInstructions
Edit box for uninstall instructions.
Package * mPackage
The package to create or edit.
Detailed Description
Wizard class used to create and edit packages within the KDE AppRover GUI.
Constructor & Destructor Documentation
PackageWizard::PackageWizard (Package * package, QWidget * parent = NULL, const char * name = NULL)
Creates a package wizard to set the values of the specified package.
References AddDependency(), AddFile(), InstallChanged(), mBuildInstructions, mBuildPage, mConfigureInstructions, mConfigurePage, mDependencyList, mDependencyNameEdit, mDependencyPage, mDependencyRevisionEdit, mFileEdit, mFileList, mFilePage, mInstallInstructions, mInstallPage, mNameEdit, mNamePage, mPackage, mUninstallInstructions, mUninstallPage, mUnpackInstructions, mUnpackPage, NameChanged(), RemoveDependency(), RemoveFile(), RevisionChanged(), and UninstallChanged().
Member Function Documentation
void PackageWizard::accept () [protected, virtual, slot]
Overrides KWizard::accept in order to save the data from the last page to the package.
References Package::AddUninstallInstruction(), Package::ClearUninstallInstructions(), mPackage, and mUninstallInstructions.
void PackageWizard::AddDependency () [slot]
Uses the data from the dependency edit box to add a new dependency to the dependency list widget.
References mDependencyList, mDependencyNameEdit, and mDependencyRevisionEdit.
Referenced by PackageWizard().
void PackageWizard::AddFile () [slot]
Uses the data from the filename edit box to add a new filename to the file list widget. After adding the file, the "next" button is enabled.
References mFileEdit, and mFileList.
Referenced by PackageWizard().
void PackageWizard::back () [protected, virtual, slot]
Overrides KWizard::back in order to clear the data from each page and the package.
References Package::ClearBuildInstructions(), Package::ClearConfigureInstructions(), Package::ClearDependencies(), Package::ClearInstallInstructions(), Package::ClearSourceFiles(), Package::ClearUninstallInstructions(), Package::ClearUnpackInstructions(), mBuildInstructions, mBuildPage, mConfigureInstructions, mConfigurePage, mDependencyList, mDependencyNameEdit, mDependencyPage, mDependencyRevisionEdit, mFileEdit, mFileList, mFilePage, mInstallInstructions, mInstallPage, mPackage, mUninstallInstructions, mUninstallPage, mUnpackInstructions, and mUnpackPage.
void PackageWizard::InstallChanged () [slot]
Called when the install instructions are changed in order to enable or disable the "next" button.
References mInstallInstructions.
Referenced by PackageWizard().
void PackageWizard::NameChanged (const QString & newName) [slot]
Parameters:
newName - the value of the package name
Sets the name of the package and enables/disables the "next" button when applicable.
References Package::GetRevision(), Revision::GetString(), mPackage, and Package::SetName().
Referenced by PackageWizard().
void PackageWizard::next () [protected, virtual, slot]
Overrides KWizard::next in order to save the data from each page to the package.
Todo:
: use paragraph option for text to separately add instructions
Todo:
update package wizard for dependency types
References Package::AddBuildInstruction(), Package::AddConfigureInstruction(), Package::AddDependency(), Package::AddInstallInstruction(), Package::AddSourceFile(), Package::AddUnpackInstruction(), Package::ClearBuildInstructions(), Package::ClearConfigureInstructions(), Package::ClearDependencies(), Package::ClearInstallInstructions(), Package::ClearSourceFiles(), Package::ClearUnpackInstructions(), mBuildInstructions, mBuildPage, mConfigureInstructions, mConfigurePage, mDependencyList, mDependencyPage, mFileList, mFilePage, mInstallInstructions, mInstallPage, mPackage, mUnpackInstructions, and mUnpackPage.
void PackageWizard::RemoveDependency () [slot]
Removes the selected dependency from the dependency list widget.
References mDependencyList.
Referenced by PackageWizard().
void PackageWizard::RemoveFile () [slot]
Removes the selected file from the file list widget and disables the "next" button if the list becomes empty.
References mFileList.
Referenced by PackageWizard().
void PackageWizard::RevisionChanged (const QString & newRevision) [slot]
Parameters:
newRevision - the value of the package revision
Sets the revision of the package and enables/disables the "next" button when applicable.
References Package::GetName(), mPackage, and Package::SetRevision().
Referenced by PackageWizard().
void PackageWizard::showPage (QWidget * page)
Parameters:
page - the page to show
Overrides QWizard::showPage in order to properly intialize focus and disable the "next" button when applicable.
References Package::GetName(), Package::GetRevision(), Revision::GetString(), mBuildInstructions, mBuildPage, mConfigureInstructions, mConfigurePage, mDependencyNameEdit, mDependencyPage, mFileEdit, mFileList, mFilePage, mInstallInstructions, mInstallPage, mNameEdit, mNamePage, mPackage, mUninstallInstructions, mUninstallPage, mUnpackInstructions, and mUnpackPage.
void PackageWizard::UninstallChanged () [slot]
Called when the uninstall instructions are changed in order to enable or disable the "finish" button.
References mUninstallInstructions.
Referenced by PackageWizard().
The documentation for this class was generated from the following files:
kPackageWizard.h
kPackageWizard.cpp