AppRover: ActionDescription Class Reference
ActionDescription Class Reference
Class reponsible representing an action to be performed on a package.
#include <ActionDescription.h>
Public Member Functions
string GetOldRevision ()
void SetOldRevision (string revision)
string GetNewRevision ()
void SetNewRevision (string revision)
string GetPackageName ()
void SetPackageName (string name)
string GetError ()
void SetError (string errorMsg)
ActionType GetAction ()
void SetAction (ActionType action)
int GetNumFeatures () const
const FeatureOption * GetFeature (int featureNumber) const
void SetFeatures (const FeatureOptionVector &features)
bool operator== (const ActionDescription &refAction) const
Private Attributes
string mOldRevision
the already installed revision of the affected application
string mNewRevision
the revision to be [partially] installed
string mPackageName
the name of the affected application
string mErrorMessage
the problem with processing the request
ActionType mAction
the action that will be performed on the application
FeatureOptionVector mFeatures
the list of optional features relevant to the application
Detailed Description
Class reponsible representing an action to be performed on a package.
Member Function Documentation
ActionType ActionDescription::GetAction ()
Returns:
the action to be performed on the affected application
References mAction.
Referenced by AppRover::Install().
string ActionDescription::GetError ()
Returns:
a string describing the error with processing
References mErrorMessage.
const FeatureOption * ActionDescription::GetFeature (int featureNumber) const
Parameters:
featureNumber - the index into the list of optional feature relevant to the affected application
Returns:
the feature option at the desired location
NULL if the featureNumber is invalid
References mFeatures.
string ActionDescription::GetNewRevision ()
Returns:
string containing the revision to be [partially] installed for the affected application
References mNewRevision.
int ActionDescription::GetNumFeatures () const
Returns:
the number of optional features relevant to the affected application
References mFeatures.
string ActionDescription::GetOldRevision ()
Returns:
string containing the currently installed revision of the affected application
References mOldRevision.
string ActionDescription::GetPackageName ()
Returns:
the name of the affected application
References mPackageName.
bool ActionDescription::operator== (const ActionDescription & refAction) const
Parameters:
refAction - the action description to compare against
Returns:
true if package name, revisions, and action are the same
References mAction, mNewRevision, mOldRevision, and mPackageName.
void ActionDescription::SetAction (ActionType action)
Parameters:
action - the action to be performed on the affected application
References mAction.
Referenced by AppRover::Clean(), AppRover::Install(), and AppRover::Uninstall().
void ActionDescription::SetError (string errorMsg)
Parameters:
name - a string describing the error with processing
References mAction, and mErrorMessage.
Referenced by AppRover::Install().
void ActionDescription::SetFeatures (const FeatureOptionVector & features)
Parameters:
features - the list of optional feature associated with the affected application
References mFeatures.
Referenced by AppRover::Install().
void ActionDescription::SetNewRevision (string revision)
Parameters:
revision - the revision to be [partially] installed for the affected application
References mNewRevision.
Referenced by AppRover::Install().
void ActionDescription::SetOldRevision (string revision)
Parameters:
revision - the currently installed revision of the affected application
References mOldRevision.
Referenced by AppRover::Clean(), AppRover::Install(), and AppRover::Uninstall().
void ActionDescription::SetPackageName (string name)
Parameters:
name - the name of the affected application
References mPackageName.
Referenced by AppRover::Clean(), AppRover::Install(), and AppRover::Uninstall().
The documentation for this class was generated from the following files:
ActionDescription.h
ActionDescription.cpp