AppRover: InstalledFile Class Reference
InstalledFile Class Reference
A class describing a file installed by a package.
#include <InstalledFile.h>
Public Member Functions
InstalledFile (string filename)
string GetFilename () const
void SetFilename (string filename)
string GetBackupFilename () const
string GetChecksum () const
void SetChecksum (string checksum)
bool IsAnInheritedFile () const
void SetInherited (bool inherited)
bool NeedsBackedUp () const
bool IsABackupFile () const
void SetBackup (bool backupState)
bool Save (xmlNodePtr parentNode)
bool Load (xmlNodePtr fileNode)
bool operator== (const InstalledFile &refFile) const
bool operator< (const InstalledFile &refFile) const
Private Attributes
string mFilename
The full path of this file.
string mFilePart
The filename portion without the path.
string mDirectory
The directory where this file is located.
string mChecksum
The checksum for this file.
bool mIsABackupFile
Is this file a backup copy of another installed file.
bool mIsAnInheritedFile
Is this a file whose ownership was transferred.
Detailed Description
A class describing a file installed by a package.
Constructor & Destructor Documentation
InstalledFile::InstalledFile (string filename)
Parameters:
filename - the absolute path of the installed file
References mChecksum, mFilename, mIsABackupFile, and mIsAnInheritedFile.
Member Function Documentation
string InstalledFile::GetBackupFilename () const
Returns:
the absolute path that would identify a backup of this file
References mDirectory, and mFilePart.
string InstalledFile::GetChecksum () const
Returns:
the checksum of this file
References mChecksum.
Referenced by NeedsBackedUp().
string InstalledFile::GetFilename () const
Returns:
the absolute path of the installed file
References mFilename.
bool InstalledFile::IsABackupFile () const
Returns:
the backup state of this file
References mIsABackupFile.
bool InstalledFile::IsAnInheritedFile () const
Returns:
the inherited state of this file
References mIsAnInheritedFile.
bool InstalledFile::Load (xmlNodePtr fileNode)
Parameters:
fileNode - the XML DOM node containing the file data
Returns:
false if fileNode is NULL or there is a format error
Loads the file data from the specified node.
References mChecksum, mIsABackupFile, mIsAnInheritedFile, and SetFilename().
Referenced by InstallEntry::LoadFileList().
bool InstalledFile::NeedsBackedUp () const
Returns:
true if this file has data that may need protection from overwriting
References GetChecksum(), mChecksum, mFilename, mFilePart, and mIsABackupFile.
bool InstalledFile::operator< (const InstalledFile & refFile) const
Parameters:
refFile - the installed file to compare against
Returns:
true if the filename of this file precedes refFile's filename
References mDirectory, and mFilePart.
bool InstalledFile::operator== (const InstalledFile & refFile) const
Parameters:
refFile - the installed file to compare against
Returns:
true if filenames are the same
References mFilename.
bool InstalledFile::Save (xmlNodePtr parentNode)
Parameters:
parentNode - the parent XML DOM node for the file node
Returns:
false if parentNode is NULL
Saves the file data as a child node of the specified parent.
References mChecksum, mFilename, mIsABackupFile, and mIsAnInheritedFile.
void InstalledFile::SetBackup (bool backupState)
Parameters:
backupState - the backup state of this file
References mIsABackupFile.
Referenced by InstallEntry::TransferFilesTo().
void InstalledFile::SetChecksum (string checksum)
Parameters:
checksum - the checksum of this file
References mChecksum.
Referenced by InstallEntry::AddInstalledFile(), and InstallEntry::TransferFilesTo().
void InstalledFile::SetFilename (string filename)
Parameters:
filename - the absolute path of the installed file
References mDirectory, mFilename, and mFilePart.
Referenced by Load().
void InstalledFile::SetInherited (bool inherited)
Parameters:
inherited - the inherited state of this file
References mIsAnInheritedFile.
Referenced by InstallEntry::TransferFilesTo().
The documentation for this class was generated from the following files:
InstalledFile.h
InstalledFile.cpp