AppRover: Repository Class Reference
Repository Class Reference
Container class for handling packages stored in a particular location.
#include <Repository.h>
Public Member Functions
RepositoryStatusType Save () const
RepositoryStatusType Load (string direcotry)
Package * FindMostCurrentPackage (string packageName, const PackageDependency *dependency=NULL)
Package * GetPackage (string packageName, string revision)
Package * GetPrecedingPackage (string packageName, string revision)
string GetDirectory () const
void SetDirectory (string directory)
bool AddPackage (Package *package)
int NumPackages () const
string GetPackageName (int packageIndex) const
string Synchronize ()
bool SetSyncProtocol (string protocol)
bool SetSyncLocation (string location)
bool IsLocal () const
Private Attributes
string mSyncProtocol
The name of the protocol used to synchronize with remotely.
string mSyncLocation
Remote location to which this repository should be synchronized.
string mDirectory
Directory where the local copy of the repository is stored.
PackageIndexVector mPackages
List of packages available in this repository.
Detailed Description
Container class for handling packages stored in a particular location.
Member Function Documentation
bool Repository::AddPackage (Package * package)
Parameters:
package - the package to add to the repository
Returns:
false if package is NULL or package duplicates another package
Adds the specified package to the repository. If no package index exists for this package, one will be created.
References PackageIndex::AddPackage(), Package::GetName(), Package::GetRevision(), Revision::GetString(), mDirectory, mPackages, Save(), and PackageIndex::SetBaseLocation().
Package * Repository::FindMostCurrentPackage (string packageName, const PackageDependency * dependency = NULL)
Parameters:
packageName - the name of the package to find
dependency - the dependency requirements
Returns:
pointer to the package with the specified name and latest revision
NULL if the packageName is not recognized or no revision is available.
Finds the latest revision of the package with the specified name. If dependency is non-null, it locates the most current revision which statisfies the dependency.
References mPackages.
string Repository::GetDirectory () const
Returns:
the directory containing the repository config file
References mDirectory.
Referenced by AppRover::SynchronizeRepositories().
Package * Repository::GetPackage (string packageName, string revision)
Parameters:
packageName - the name of the package to retrieve
revision - the revision of the package to retrieve
Returns:
package with the specified name and revision
NULL if no package with the specified name and revision could be found
References mPackages.
string Repository::GetPackageName (int packageIndex) const
Parameters:
packageIndex the index to the list of package names
Returns:
the name of the package at the specified index
"" if the index is invalid
References mPackages.
Package * Repository::GetPrecedingPackage (string packageName, string revision)
Parameters:
packageName - the name of the package to retrieve
revision - the revision which comes after the desired revision
Returns:
package with the specified name with revision preceding the specified one
NULL if no package with the specified name and revision constraint could be found
References mPackages.
bool Repository::IsLocal () const
Returns:
true if this repository does not have a synchronization location
References mSyncLocation.
RepositoryStatusType Repository::Load (string directory)
Parameters:
directory - the directory containing the repository config file
Returns:
REPO_DIR_NOT_SPECIFIED if directory is ""
REPO_FILE_MISSING if the config file could not be read
REPO_FILE_FORMAT_ERROR if there is a format error in the file
REPO_OK otherwise
Loads the repository data from the repository config file in the specified directory.
References PackageIndex::Load(), mDirectory, mPackages, mSyncLocation, mSyncProtocol, and PackageIndex::SetBaseLocation().
Referenced by AppRover::AppRover(), and AppRover::SynchronizeRepositories().
int Repository::NumPackages () const
Returns:
the number of distinct package names in the repository
References mPackages.
RepositoryStatusType Repository::Save () const
Returns:
REPO_FILE_NOT_WRITABLE if the repository file cannot be written
REPO_OK otherwise
Saves the repository data to the repository config file in the previously specified directory.
References mDirectory, mPackages, mSyncLocation, and mSyncProtocol.
Referenced by AppRover::AddNewRepository(), AddPackage(), AppRover::AppRover(), and AppRover::SynchronizeRepositories().
void Repository::SetDirectory (string directory)
Parameters:
directory - the directory to hold the repository
Sets the config directory for the repository. If the directory does not exist, it will be created.
References mDirectory.
Referenced by AppRover::AddNewRepository().
bool Repository::SetSyncLocation (string location)
Parameters:
location - the remote location used to synchronize this repository ("" for local repository)
Returns:
true;
Todo:
Start checking if location format matches protocol
References mSyncLocation.
bool Repository::SetSyncProtocol (string protocol)
Parameters:
protocol - the protocol to use for syncronization to a remote repository
Returns:
true if the protocol is supported ("cvs", "rsync", or "package")
References mSyncProtocol.
string Repository::Synchronize ()
Returns:
string containing an error message (if any)
Uses the protocol specified in mSyncProtocol to update this repository to match the contents of the location specified in mSyncLocation. This does nothing if the repository is local, or either mSyncProtocol or mSyncLocation is unspecified. Cvs and package protocols are supported. Rsync support is currently not implemented.
Todo:
Do actual rsync synchronization
References Fetcher::Fetch(), Interpreter::Interpret(), mDirectory, mSyncLocation, and mSyncProtocol.
The documentation for this class was generated from the following files:
Repository.h
Repository.cpp