AppRover: AppRoverKWindow Class Reference
AppRoverKWindow Class Reference
Window class of the KDE AppRover GUI.
#include <kAppRover.h>
Public Slots
void Install ()
void Uninstall ()
void CreateNewPackage ()
Public Member Functions
AppRoverKWindow (const char *title)
Private Member Functions
void FillOutPackageList ()
Private Attributes
KListView * mPackageList
the view which lists the available packages
AppRover * mAppRover
the AppRover work horse object
Detailed Description
Window class of the KDE AppRover GUI.
Constructor & Destructor Documentation
AppRoverKWindow::AppRoverKWindow (const char * title)
Initializes the window and creates the AppRover object to handle the bulk of the processing.
References CreateNewPackage(), FillOutPackageList(), Install(), Interpreter::Interpret(), mAppRover, mPackageList, and Uninstall().
Member Function Documentation
void AppRoverKWindow::CreateNewPackage () [slot]
Creates a new package by invoking a PackageWizard.
References AppRover::AddNewPackage(), FillOutPackageList(), and mAppRover.
Referenced by AppRoverKWindow().
void AppRoverKWindow::FillOutPackageList () [private]
Obtains a list of packages from the AppRover and uses it to populate the package list widget.
Todo:
Clean this up so it doesn't do so many allocations / deallocations
References AppRover::GetInstalledRevisionNumber(), AppRover::GetPackageName(), mAppRover, mPackageList, and AppRover::NumPackages().
Referenced by AppRoverKWindow(), CreateNewPackage(), Install(), and Uninstall().
void AppRoverKWindow::Install () [slot]
Installs the packages currently selected in the package list widget.
References FillOutPackageList(), AppRover::Install(), mAppRover, and mPackageList.
Referenced by AppRoverKWindow().
void AppRoverKWindow::Uninstall () [slot]
Uninstalls the packages currently selected in the package list widget.
References FillOutPackageList(), mAppRover, mPackageList, and AppRover::Uninstall().
Referenced by AppRoverKWindow().
The documentation for this class was generated from the following files:
kAppRover.h
kAppRover.cpp