AppRover: InstallLog Class Reference
InstallLog Class Reference
Class for managing the entries of all packages which have been at least partially installed.
#include <InstallLog.h>
Public Member Functions
InstallLogStatusType Save (string filename)
InstallLogStatusType Load (string filename)
bool Satisfies (const PackageDependency *dependency) const
bool AddEntry (InstallEntry *newEntry)
InstallEntry * FindEntry (string packageName, string packageRevision)
void GetInstalledEntries (string packageName, vector< InstallEntry * > &results)
InstallEntry * FindPartiallyInstalledEntry (string packageName, string packageRevision)
InstallEntry * FindOldestInstalledEntry (string packageName)
InstallEntry * FindNextOldestInstalledEntry (InstallEntry *entry)
InstallEntry * FindInstalledSlotOccupant (string packageName, string slot)
bool DeleteEntry (string packageName, string packageRevision)
bool DeleteEntry (InstallEntry *entry, bool removeRevDeps=true)
string GetRevisionInstalled (string packageName)
bool RemovePartiallyInstalledSlotMates (InstallEntry *entry, string workDirectory)
void RegisterReverseDependency (string packageName, string revision, const PackageDependency *dependency)
void ReleaseReverseDependenciesTo (string packageName, string revision)
InstallEntryVector GetPackagesUsingFeature (string featureName)
InstallEntryVector GetPartiallyInstalledPackages ()
InstallEntryVector GetUnneededPackages ()
Private Attributes
InstallEntryVector mInstallEntries
List of all [partially] installed packages in the system.
Detailed Description
Class for managing the entries of all packages which have been at least partially installed.
Member Function Documentation
bool InstallLog::AddEntry (InstallEntry * newEntry)
Parameters:
newEntry - the entry to add to the log
Returns:
false if the entry is NULL
Adds an entry to the list of entries.
References mInstallEntries.
Referenced by AppRover::Install().
bool InstallLog::DeleteEntry (string packageName, string packageRevision)
Parameters:
packageName - name of the package recorded in the entry
packageRevision - revision of the package recorded in the entry
Returns:
false if no entry records a package with the specified name and revision
Deletes an entry containing a package with the specified name and revision. Removes all reverse dependencies which link to this entry.
References mInstallEntries.
Referenced by AppRover::Clean(), AppRover::Install(), RemovePartiallyInstalledSlotMates(), and AppRover::Uninstall().
bool InstallLog::DeleteEntry (InstallEntry * entry, bool removeRevDeps = true)
Parameters:
entry - the entry to remove from the log
removeRevDeps - should reverse dependencies that point to this package be removed
Returns:
false if the entry was not found in the log
Removes the specifed entry from the log and removes the package from reverse dependencies of all other installed packages.
References InstallEntry::GetName(), InstallEntry::GetNumDependencies(), InstallEntry::GetRevision(), Revision::GetString(), and mInstallEntries.
InstallEntry * InstallLog::FindEntry (string packageName, string packageRevision)
Parameters:
packageName - name of the package recorded in the entry
packageRevision - revision of the package recorded in the entry
Returns:
the entry contaiing the specified package and revision
NULL if no entry records a package with the specified name and revision
References mInstallEntries.
Referenced by AppRover::Install(), and AppRover::Update().
InstallEntry * InstallLog::FindInstalledSlotOccupant (string packageName, string slot)
Parameters:
packageName - name of the package
slot - the slot which the requested package occupies
Returns:
the installed entry with the given name that occupies the specified slot
NULL if the package has not been installed or does not occupy the specifed slot
References mInstallEntries.
Referenced by AppRover::Install().
InstallEntry * InstallLog::FindNextOldestInstalledEntry (InstallEntry * entry)
Parameters:
entry - the install entry used as a reference for find the next oldest installed entry
Returns:
the oldest installed entry which is newer than the reference entry
NULL if entry is NULL or is the newest installed entry
References InstallEntry::GetName(), InstallEntry::GetRevision(), and mInstallEntries.
Referenced by AppRover::Uninstall().
InstallEntry * InstallLog::FindOldestInstalledEntry (string packageName)
Parameters:
packageName - name of the package recorded in the entry
Returns:
the entry contaiing the specified package and a revision older than the revision of any other entry for the specified package
NULL if no entry records a package with the specified name
References InstallEntry::GetRevision(), and mInstallEntries.
Referenced by AppRover::Uninstall().
InstallEntry * InstallLog::FindPartiallyInstalledEntry (string packageName, string packageRevision)
Parameters:
packageName - name of the package recorded in the entry
packageRevision - revision of the package recorded in the entry
Returns:
the entry contaiing the specified package and revision
NULL if no entry records a package with the specified name and revision
References mInstallEntries.
Referenced by AppRover::Install().
void InstallLog::GetInstalledEntries (string packageName, vector< InstallEntry * > & results)
Parameters:
packageName - name of the package
results - (output) the installed entries of the specified package
Finds all installed versions of the package and stores the entries in results.
References mInstallEntries.
Referenced by AppRover::ExcludeFromUpdates(), and AppRover::Purify().
InstallEntryVector InstallLog::GetPackagesUsingFeature (string featureName)
Parameters:
featureName - the name of the optional feature to locate in the entries
Returns:
list of packages can use the optional feature
References mInstallEntries.
Referenced by AppRover::ActivateFeature(), and AppRover::ActivateFeatureForPackage().
InstallEntryVector InstallLog::GetPartiallyInstalledPackages ()
Returns:
list of all packages which have only been partially installed
References mInstallEntries.
Referenced by AppRover::Clean().
string InstallLog::GetRevisionInstalled (string packageName)
Parameters:
packageName - name of the package recorded in the entry
Returns:
"" if the package has not been installed in the system
Otherwise, the revision string of the specified installed package
References mInstallEntries.
Referenced by AppRover::PopulatePackageList().
InstallEntryVector InstallLog::GetUnneededPackages ()
Returns:
list of all packages which were not explicitly installed and are not dependencies of explicitly installed packages
Todo:
Add an input list of things to ignore
References mInstallEntries.
Referenced by AppRover::Clean().
InstallLogStatusType InstallLog::Load (string filename)
Parameters:
filename - the name of the file containing the installation log
Returns:
LOG_FILE_NOT_SPECIFIED if filename is ""
LOG_FILE_MISSING if the file does not exist
LOG_FILE_FORMAT_ERROR if there is a problem with the data
LOG_OK if successful
Loads the installation log from the specified file.
References InstallEntry::Load(), and mInstallEntries.
Referenced by AppRover::AppRover().
void InstallLog::RegisterReverseDependency (string packageName, string revision, const PackageDependency * dependency)
Parameters:
packageName - the name of the package with the specified dependency
revision - the revision of the package with the specified dependency
dependency - package dependency used to determine the recipient of the reverse dependency
Uses the dependency to locate a satisfiying package and associates the specified package name and revision as a reverse dependency.
Install dependencies are moot after package install, so no reverse dependencies are generated for them.
Todo:
Need to find best entry which satifies the dependency
References PackageDependency::GetName(), PackageDependency::GetType(), PackageDependency::IsSatisfiedBy(), and mInstallEntries.
Referenced by AppRover::Install().
void InstallLog::ReleaseReverseDependenciesTo (string packageName, string packageRevision)
Parameters:
packageName - name of the target package
packageRevision - revision of the target package
Deletes reverse dependencies which point to a package with the specified name and revision. If a single entry has more than one applicable reverse dependency, only one of them is removed.
References mInstallEntries.
Referenced by InstallEntry::ClearDependencies().
bool InstallLog::RemovePartiallyInstalledSlotMates (InstallEntry * entry, string workDirectory)
Parameters:
entry - the package occupying the slot to be cleaned
workDirectory - the top level directory where builds are done
Returns:
false if entry is NULL
Examines the package slot for the specified entry and clears out any other entries which occupy the same slot and are in a partially installed state.
References DeleteEntry(), InstallEntry::GetName(), InstallEntry::GetSlot(), Interpreter::Interpret(), and mInstallEntries.
Referenced by AppRover::Install().
bool InstallLog::Satisfies (const PackageDependency * dependency) const
Parameters:
dependency - the dependency that need to be resolved
Returns:
true if a package has been installed that satisfies the dependency
Determines whether the dependency has been satisfied by the installed packages.
Todo:
Need to add support here for block packages
References PackageDependency::GetName(), PackageDependency::IsSatisfiedBy(), and mInstallEntries.
Referenced by AppRover::Install().
InstallLogStatusType InstallLog::Save (string filename)
Parameters:
filename - the name of the file to hold the installation log
Returns:
LOG_FILE_NOT_SPECIFIED if filename is ""
LOG_FILE_NOT_WRITABLE if the file could not be opened for writing
LOG_OK if successful
Saves the installation log into the specified file.
References mInstallEntries.
Referenced by AppRover::AppRover(), AppRover::BuildPackage(), AppRover::Clean(), AppRover::ConfigurePackage(), AppRover::ExcludeFromUpdates(), AppRover::FetchPackage(), AppRover::Install(), AppRover::InstallPackage(), AppRover::Purify(), AppRover::Uninstall(), and AppRover::UnpackPackage().
The documentation for this class was generated from the following files:
InstallLog.h
InstallLog.cpp