AppRover: SourceFile Class Reference
SourceFile Class Reference
A class describing a package source file.
#include <SourceFile.h>
Public Member Functions
SourceFile (string location)
SourceFile (const SourceFile *refFile)
string GetLocation () const
bool SetLocation (string location)
string GetCheckSum () const
void SetCheckSum (string checksum)
const BooleanExpression & GetCondition () const
void SetCondition (const BooleanExpression &condition)
bool Save (xmlNodePtr parentNode)
bool Load (xmlNodePtr fileNode)
bool IsActive (const FeatureOptionVector &features) const
bool IsEmbedded () const
void SetContents (string contents)
bool ExtractContents (string directory)
Private Attributes
string mLocation
The remote location of this file, or if embedded file, just the filename.
string mCheckSum
The checksum for this file.
BooleanExpression mCondition
The expression which indicates whether this file is required.
string mContents
Contents of an embedded file.
Detailed Description
A class describing a package source file.
Constructor & Destructor Documentation
SourceFile::SourceFile (string location)
Parameters:
location - the remote location of the source file
References mLocation.
SourceFile::SourceFile (const SourceFile * refFile)
Parameters:
refFile - SourceFile to clone
References mCheckSum, mCondition, mContents, and mLocation.
Member Function Documentation
bool SourceFile::ExtractContents (string directory)
Saves the embedded file contents to the specified directory with the filename determined by the contents of the location field.
Parameters:
contents - the contents of the embedded file
Returns:
true on success
false if file is not embedded or other error
References mContents, and mLocation.
string SourceFile::GetCheckSum () const
Returns:
the checksum of this file
References mCheckSum.
const BooleanExpression & SourceFile::GetCondition () const
Returns:
the expression indicating whether this file is required
References mCondition.
string SourceFile::GetLocation () const
Returns:
the remote location of the source file
References mLocation.
bool SourceFile::IsActive (const FeatureOptionVector & features) const
Parameters:
features - the features used to evaluate whether this file is required
Returns:
the result of evaluating the condition with respect to the value of the features
true if the condition is empty
References BooleanExpression::EvaluatesToTrue(), BooleanExpression::IsEmpty(), and mCondition.
bool SourceFile::IsEmbedded () const
Returns:
true if the file contents are embedded in this object, false otherwise
References mContents.
bool SourceFile::Load (xmlNodePtr fileNode)
Parameters:
fileNode - the XML DOM node containing the file data
Returns:
false if fileNode is NULL or there is a format error
Loads the file data from the specified node.
References mCheckSum, mCondition, mContents, mLocation, and BooleanExpression::ParseFromString().
Referenced by Package::Load().
bool SourceFile::Save (xmlNodePtr parentNode)
Parameters:
parentNode - the parent XML DOM node for the file node
Returns:
false if parentNode is NULL
Saves the file data as a child node of the specified parent.
References BooleanExpression::GetString(), mCheckSum, mCondition, mContents, and mLocation.
void SourceFile::SetCheckSum (string checksum)
Parameters:
checksum - the checksum of this file
References mCheckSum.
void SourceFile::SetCondition (const BooleanExpression & condition)
Parameters:
condition - the expression indicating whether this file is required
References mCondition.
Referenced by Package::Package().
void SourceFile::SetContents (string contents)
Sets the embedded file contents to the specified string. If the string is empty, the contents are cleared and this source file will no longer be embedded.
Parameters:
contents - the contents of the embedded file
References mContents.
bool SourceFile::SetLocation (string location)
Parameters:
location - the remote location of the source file
Returns:
true if the location is properly formatted (currently only checks for a lack of whitespace)
References mLocation.
The documentation for this class was generated from the following files:
SourceFile.h
SourceFile.cpp