AppRover: PackageIndex Class Reference
PackageIndex Class Reference
A storage class for tracking and maintaining package revisions.
#include <PackageIndex.h>
Public Member Functions
bool Save (xmlNodePtr parentNode) const
bool Load (xmlNodePtr packageIndexNode)
Package * GetPackage (string revision)
Package * GetMostCurrentPackage (const PackageDependency *dependency=NULL)
Package * GetPrecedingPackage (string revision)
void SetBaseLocation (string baseLocation)
bool AddPackage (Package *package)
string GetName () const
bool ContainsRevision (string revision) const
Private Attributes
string mPackageName
The name of the application pertaining to the list of packages.
string mBaseLocation
The directory containing the list file for this index.
vector< Revision > mPackageRevisions
The list of revisions available for this application.
vector< string > mPackageFilenames
The list of files containing package data for this application.
PackageVector mLoadedPackages
The list of packages whose info has been already loaded from disk.
Detailed Description
A storage class for tracking and maintaining package revisions.
Member Function Documentation
bool PackageIndex::AddPackage (Package * package)
Parameters:
package - a package to add to this index
Returns:
false if 1) package is NULL 2) the package is missing its name or revision 3) the index contains a package with the same revision as the revision of package 4) the package has the wrong name
This adds a package to the list of packages handled by this index. If this is the first package, it is used to set the name of the package index.
References ContainsRevision(), Package::GetName(), Package::GetRevision(), Revision::GetString(), mLoadedPackages, mPackageFilenames, mPackageName, and mPackageRevisions.
Referenced by Repository::AddPackage().
bool PackageIndex::ContainsRevision (string revision) const
Parameters:
revision - the revision potentially handled by this index
Returns:
- true if the specified revision is contained in one of the packages handled by this index
References mPackageRevisions.
Referenced by AddPackage().
Package * PackageIndex::GetMostCurrentPackage (const PackageDependency * dependency = NULL)
Parameters:
dependency - the dependency requirements
Returns:
a pointer to the package with the latest revision number
NULL if there are not entries in the index, or the package cannot be loaded.
If dependency is non-null, it locates the most current revision which statisfies the dependency.
References PackageDependency::IsSatisfiedBy(), Package::Load(), mBaseLocation, mLoadedPackages, mPackageFilenames, mPackageName, and mPackageRevisions.
string PackageIndex::GetName () const
Returns:
the name of the package managed by this index
References mPackageName.
Referenced by Save().
Package * PackageIndex::GetPackage (string revision)
Parameters:
revision - the revision of the package to retrieve
Returns:
the package with the specified revision
NULL if the revision is unknown or the package could not be loaded
References mBaseLocation, mLoadedPackages, mPackageFilenames, mPackageName, and mPackageRevisions.
Package * PackageIndex::GetPrecedingPackage (string revision)
Parameters:
revision - a revision following the desired revision
Returns:
a pointer to the package with the latest revision number preceding the specified one
NULL if there are not entries in the index, or the package cannot be loaded.
References Package::Load(), mBaseLocation, mLoadedPackages, mPackageFilenames, mPackageName, mPackageRevisions, and Revision::Set().
bool PackageIndex::Load (xmlNodePtr packageIndexNode)
Parameters:
packageIndexNode - the XML DOM node containing the package index data
Returns:
false if packageIndexNode is NULL or there is a format error
Loads the package index data from the specified node.
References mPackageFilenames, mPackageName, mPackageRevisions, and Revision::Set().
Referenced by Repository::Load().
bool PackageIndex::Save (xmlNodePtr parentNode) const
Parameters:
parentNode - the parent XML DOM node for the package index node
Returns:
false if parentNode is NULL
Saves the package index data as a child node of the specified parent.
References GetName(), mBaseLocation, mLoadedPackages, mPackageFilenames, mPackageName, and mPackageRevisions.
void PackageIndex::SetBaseLocation (string baseLocation)
Parameters:
baseLocation - the parent to the package directory
This sets the directory which will be used as a parent to the directory where the packages are stored. The package directory will be created if it does not exist.
References mBaseLocation, and mPackageName.
Referenced by Repository::AddPackage(), and Repository::Load().
The documentation for this class was generated from the following files:
PackageIndex.h
PackageIndex.cpp