AppRover: Revision Class Reference
Revision Class Reference
A simple class for handling package revision strings.
#include <Revision.h>
Public Member Functions
Revision (string revision)
bool IsSet () const
Revision & operator= (const Revision &src)
bool operator< (const Revision &refRevision) const
bool operator<= (const Revision &refRevision) const
bool operator== (const Revision &refRevision) const
bool operator>= (const Revision &refRevision) const
bool operator> (const Revision &refRevision) const
string GetString () const
void Set (string revision)
Private Member Functions
void SetValues ()
Private Attributes
string mRevisionStr
The contents of this revision in a readable string.
int mAlphaNumber
The alpha number of this revision (i.e. alpha 1, alpha 2, etc.).
int mBetaNumber
The beta number of this revision (i.e. beta 1, beta 2, etc.).
int mRCNumber
The release candidate number of this revision (i.e. RC 1, RC 2, etc.).
vector< int > mVersionParts
List of the leading numeric components in the application's version.
string mRemnant
Non-numeric revision suffix aside from alpha, beta, and rc.
Detailed Description
A simple class for handling package revision strings.
A revision consists of the version of an application combined with and indicator of how many times a package for this application has been redone (such as "1.00beta1", "1.00", "1.00-r1", "1.00-r2", "1.02")
Constructor & Destructor Documentation
Revision::Revision (string revision)
Parameters:
revision - the string representation of this revision
References mRevisionStr, and SetValues().
Member Function Documentation
string Revision::GetString () const
Returns:
the string representation of this revision
References mRevisionStr.
Referenced by Repository::AddPackage(), PackageIndex::AddPackage(), Package::Build(), InstallEntry::ClearDependencies(), Package::Configure(), InstallLog::DeleteEntry(), Package::Fetch(), PackageDependency::GetDependentRevision(), PackageDependency::GetDependentString(), PackageDependency::GetMaxRevision(), PackageDependency::GetMinRevision(), PackageDependency::GetString(), Package::Install(), AppRover::Install(), PackageWizard::NameChanged(), Package::Package(), PackageDependency::Save(), Package::Save(), InstallEntry::Save(), PackageWizard::showPage(), InstallEntry::Uninstall(), AppRover::Uninstall(), Package::Unpack(), and AppRover::Update().
bool Revision::IsSet () const
Returns:
false if this revision is empty (unspecified)
References mRevisionStr.
Referenced by PackageDependency::GetString(), PackageDependency::IsSatisfiedBy(), and PackageDependency::Save().
bool Revision::operator< (const Revision & refRevision) const
Parameters:
refRevision - the revision that this revision is compared against
Returns:
true if this revision is earlier than the reference revision
To determine if a revision comes earlier, first the corresponding numeric parts of the application version are compared. If all of the corresponding parts match, the revision with fewer numeric components is considered earlier. Next, the alpha numbers are compared, followed by the beta and rc numbers. Finally, the number of times the package has been revised should be compared (currently unimplemented). All other comparison operators determine their values by using the results of this operator and checking for equality.
Todo:
Add support for checking the revision number
References mAlphaNumber, mBetaNumber, mRCNumber, mRemnant, and mVersionParts.
bool Revision::operator<= (const Revision & refRevision) const
Parameters:
refRevision - the revision that this revision is compared against
Returns:
true if this revision is earlier than or matches the reference revision
Revision & Revision::operator= (const Revision & src)
Parameters:
src - the revision to copy
Returns:
reference to this revision
References mRevisionStr.
bool Revision::operator== (const Revision & refRevision) const
Parameters:
refRevision - the revision that this revision is compared against
Returns:
true if this revision matches the reference revision
References mRevisionStr.
bool Revision::operator> (const Revision & refRevision) const
Parameters:
refRevision - the revision that this revision is compared against
Returns:
true if this revision is later than the reference revision
bool Revision::operator>= (const Revision & refRevision) const
Parameters:
refRevision - the revision that this revision is compared against
Returns:
true if this revision is later than or matches the reference revision
void Revision::Set (string revision)
Returns:
revision - the string representation of this revision
References mRevisionStr, and SetValues().
Referenced by PackageIndex::GetPrecedingPackage(), PackageIndex::Load(), PackageDependency::Load(), Package::Load(), InstallEntry::Load(), Package::Package(), PackageDependency::PackageDependency(), PackageDependency::SetDependentRevision(), Package::SetRevision(), and InstallEntry::SetRevision().
void Revision::SetValues () [private]
Parses the revision string and loads the relevant date into the version parts, and sets the alpha, beta, and release candidate numbers.
References mAlphaNumber, mBetaNumber, mRCNumber, mRemnant, mRevisionStr, and mVersionParts.
Referenced by Revision(), and Set().
The documentation for this class was generated from the following files:
Revision.h
Revision.cpp