AppRover: InstallEntry Class Reference
InstallEntry Class Reference
Class responsible for managing all data concerning a package which has been at least partially installed.
#include <InstallEntry.h>
Public Member Functions
bool Save (xmlNodePtr parentNode)
bool Load (xmlNodePtr entryNode)
string GetName () const
void SetName (string name)
const Revision & GetRevision () const
void SetRevision (string revision)
string GetSlot () const
void SetSlot (string slot)
int GetBinaryCompatabilityRevision () const
void SetBinaryCompatabilityRevision (int revision)
bool IsUnpacked () const
bool IsAtLeastUnpacked () const
void SetUnpacked ()
bool IsConfigured () const
bool IsAtLeastConfigured () const
void SetConfigured ()
bool IsBuilt () const
void SetBuilt ()
bool IsInstalled () const
void SetInstalled ()
string GetErrorMessage () const
void SetErrorMessage (string errMsg)
string Uninstall (bool backup=true)
void SetInstallListFilename (string filename)
void AddInstalledFile (string filename)
void AddInstalledSymLink (string linkname)
void AddInstalledDirectory (string directory)
bool TransferFilesTo (InstallEntry *target)
void ConsolidateFiles ()
bool PurgeLegacyFiles ()
void SetUninstallInstructions (const InstructionSequence &instructions)
void AddDependency (const PackageDependency &dependency)
void ClearDependencies (InstallLog &installLog)
int GetNumDependencies () const
const PackageDependency * GetDependency (int depNumber)
void AddReverseDependency (string packageName, string revision, const PackageDependency &forwardDependency)
void RemoveReverseDependency (string packageName, string revision, int maxEntries=1)
bool TransferReverseDependenciesTo (InstallEntry *target)
int GetNumReverseDependencies () const
string GetReverseDependencyName (int depNumber) const
bool ReverseDependencyIsStatic (int depNumber) const
bool ReverseDependenciesAreInList (const InstallEntryVector &packages) const
const FeatureOptionVector & GetFeatures () const
void AddFeature (FeatureOption *feature)
bool HasFeature (string featureName)
bool GetFeatureState (string featureName)
bool ActivateFeature (string featureName)
bool DeactivateFeature (string featureName)
bool IsExplicitlyInstalled ()
void SetExplicitlyInstalled (bool state)
bool IsExcludedFromUpdates ()
void SetExcludeFromUpdates (bool state)
Private Member Functions
bool LoadFileList ()
Private Attributes
string mPackageName
The name of the package pertaining to this entry.
Revision mPackageRevision
The revision of the package pertaining to this entry.
string mPackageSlot
The slot occupied by the package pertaining to this entry.
bool mExplicitInstall
The state of whether this installation was explicitly requested by the user.
bool mExcludeFromUpdates
Should this package be allowed to update when not necessary or expilcity stated.
int mBinaryCompatabilityRevision
Value used to track whether two revisions of a package have binary compatable interfaces.
string mPackageStatus
The state to which this package has been installed (unpacked, configured, etc).
bool mInstalledInThisSession
Indicates that this package was just installed, and its files must be recorded.
string mErrorMessage
The error message(s) generated by the last action performed on the package.
string mInstallListFilename
The name of the file listing the files installed by this package.
vector< InstalledFile * > mInstalledFiles
The files installed by this package.
vector< string > mInstalledSymLinks
The names of the symbolic links installed by this package.
vector< string > mInstalledDirectories
The names of the directories installed by this package.
InstructionSequence mUninstallInstructions
The instructions (if any) executed to remove this package from this system.
PackageDependencyVector mDependencies
The list of dependencies this package has on other packages.
PackageDependencyVector mReverseDependencies
The list of the packages which depend on this package.
FeatureOptionVector mFeatures
The list of optional features and their states used by this package.
Detailed Description
Class responsible for managing all data concerning a package which has been at least partially installed.
Member Function Documentation
bool InstallEntry::ActivateFeature (string featureName)
Parameters:
featureName - the name of the feature which is possibly used by this package
Returns:
true if the optional feature has been associated
Activates the feature in the list of features. This does not affect the current installation, but whenever this package is upgraded or reinstalled, the feature will be used.
References GetName(), and mFeatures.
void InstallEntry::AddDependency (const PackageDependency & dependency)
Parameters:
dependency - package dependency to be added to the list of this package's dependencies
References mDependencies.
Referenced by AppRover::Install().
void InstallEntry::AddFeature (FeatureOption * feature)
Parameters:
feature - optional feature to associate with this package
References mFeatures.
Referenced by AppRover::Install().
void InstallEntry::AddInstalledDirectory (string directory)
Parameters:
directory - the full path of an installed directory
Records a directory that has been installed by the package.
References mInstalledDirectories.
Referenced by Package::Install(), and TransferFilesTo().
void InstallEntry::AddInstalledFile (string filename)
Parameters:
filename - the full path of an installed file
Records a file that has been installed by the package.
References mInstalledFiles, and InstalledFile::SetChecksum().
Referenced by Package::Install().
void InstallEntry::AddInstalledSymLink (string linkname)
Parameters:
linkname - the full path of an installed symbolic link
Records a symbolic link that has been installed by the package.
References mInstalledSymLinks.
Referenced by Package::Install(), and TransferFilesTo().
void InstallEntry::AddReverseDependency (string packageName, string revision, const PackageDependency & forwardDependency)
Parameters:
packageName - name of the package which depends on this package
revision - revision of the package with depends on this package
forwardDependency - the dependency which the reverse dependency mirrors
References mReverseDependencies, PackageDependency::SetDependentName(), and PackageDependency::SetDependentRevision().
void InstallEntry::ClearDependencies (InstallLog & installLog)
Empties the list of dependencies associated with this package, and releases all reverse dependencies which point to this package.
References Revision::GetString(), mDependencies, mPackageName, mPackageRevision, and InstallLog::ReleaseReverseDependenciesTo().
Referenced by AppRover::Install().
void InstallEntry::ConsolidateFiles ()
Removes duplicate and missing files from the file list. Any backup files will be compared against the original file, and will be removed if they are the same or if the original file is missing (don't want backups of obsolete files).
References LoadFileList(), and mInstalledFiles.
Referenced by Package::Install().
bool InstallEntry::DeactivateFeature (string featureName)
Parameters:
featureName - the name of the feature which is possibly used by this package
Returns:
true if the optional feature has been associated
Deactivates the feature in the list of features. This does not affect the current installation, but whenever this package is upgraded or reinstalled, the feature will no longer be used.
References GetName(), and mFeatures.
int InstallEntry::GetBinaryCompatabilityRevision () const
Returns:
integer used to track whether to revisions have binary compatable interfaces
References mBinaryCompatabilityRevision.
Referenced by AppRover::Install().
const PackageDependency * InstallEntry::GetDependency (int depNumber)
Parameters:
depNumber - the index into the list of dependencies
Returns:
the dependency at the specified position in the list
NULL if depNumber is invalid
References mDependencies.
string InstallEntry::GetErrorMessage () const
return the last recorded error message from one of the installation stages
References mErrorMessage.
Referenced by AppRover::Install().
const FeatureOptionVector & InstallEntry::GetFeatures () const
Returns:
list of the optional features and their states associated with this package
References mFeatures.
Referenced by Package::Fetch(), InstructionSequence::HandleIfStatement(), AppRover::Install(), and Package::Unpack().
bool InstallEntry::GetFeatureState (string featureName)
Parameters:
featureName - the name of the feature which is possibly used by this package
Returns:
true if the optional feature has been associated with this package and has been activated
References GetName(), and mFeatures.
Referenced by AppRover::Install().
string InstallEntry::GetName () const
Returns:
the name of the package recorded in this log entry
References mPackageName.
Referenced by ActivateFeature(), DeactivateFeature(), InstallLog::DeleteEntry(), InstallLog::FindNextOldestInstalledEntry(), GetFeatureState(), HasFeature(), PackageDependency::IsSatisfiedBy(), InstallLog::RemovePartiallyInstalledSlotMates(), and ReverseDependenciesAreInList().
int InstallEntry::GetNumDependencies () const
Returns:
the number of dependencies associated with this package
References mDependencies.
Referenced by InstallLog::DeleteEntry().
int InstallEntry::GetNumReverseDependencies () const
Returns:
the number of reverse dependencies pertaining to this package
References mReverseDependencies.
Referenced by AppRover::Install().
string InstallEntry::GetReverseDependencyName (int depNumber) const
Parameters:
depNumber - the index into the list of reverse dependency names
Returns:
the name of the reverse dependency at the specified position in the list
NULL if depNumber is invalid
References mReverseDependencies.
Referenced by AppRover::Install().
const Revision & InstallEntry::GetRevision () const
return the revision of the package recorded in this log entry
References mPackageRevision.
Referenced by InstallLog::DeleteEntry(), InstallLog::FindNextOldestInstalledEntry(), InstallLog::FindOldestInstalledEntry(), AppRover::Install(), PackageDependency::IsSatisfiedBy(), and AppRover::Uninstall().
string InstallEntry::GetSlot () const
Returns:
string containing the slot occupied by this package
References mPackageSlot.
Referenced by InstallLog::RemovePartiallyInstalledSlotMates().
bool InstallEntry::HasFeature (string featureName)
Parameters:
featureName - the name of the feature which is possibly used by this package
Returns:
true if the optional feature has been associated with this package
References GetName(), and mFeatures.
Referenced by AppRover::Install().
bool InstallEntry::IsAtLeastConfigured () const
Returns:
- true if the package recorded in this entry has completed the configure stage and possibly the stages following configure
References IsAtLeastUnpacked(), and mPackageStatus.
Referenced by AppRover::BuildPackage(), and AppRover::Install().
bool InstallEntry::IsAtLeastUnpacked () const
Returns:
true if the package recorded in this entry has completed the unpack stage and possibly the stages following unpack
References mPackageStatus.
Referenced by AppRover::ConfigurePackage(), AppRover::Install(), and IsAtLeastConfigured().
bool InstallEntry::IsBuilt () const
Returns:
- true if the package recorded in this entry has just completed the build stage of installation
References mPackageStatus.
Referenced by AppRover::Install(), and AppRover::InstallPackage().
bool InstallEntry::IsConfigured () const
Returns:
- true if the package recorded in this entry has just completed the configure stage of installation
References mPackageStatus.
bool InstallEntry::IsExcludedFromUpdates ()
Returns:
true if this package should not be auto-updated
References mExcludeFromUpdates.
Referenced by AppRover::Update().
bool InstallEntry::IsExplicitlyInstalled ()
Returns:
true if this package was installed due to an explicit request from the user
References mExplicitInstall.
Referenced by AppRover::Install(), and AppRover::Update().
bool InstallEntry::IsInstalled () const
Returns:
true if the package has been installed on the system
References mPackageStatus.
Referenced by AppRover::Install(), and Save().
bool InstallEntry::IsUnpacked () const
Returns:
true if the package recorded in this entry has just completed the unpack stage of installation
References mPackageStatus.
bool InstallEntry::Load (xmlNodePtr entryNode)
Parameters:
entryNode - the xml DOM node to containing the install entry data
Returns:
false if entryNode is NULL, or there is a probelm with the data
true otherwise
Loads the install entry data from an XML DOM node.
References FeatureOption::Load(), InstructionSequence::Load(), PackageDependency::Load(), mBinaryCompatabilityRevision, mDependencies, mErrorMessage, mExcludeFromUpdates, mExplicitInstall, mFeatures, mInstallListFilename, mPackageName, mPackageRevision, mPackageSlot, mPackageStatus, mReverseDependencies, mUninstallInstructions, and Revision::Set().
Referenced by InstallLog::Load().
bool InstallEntry::LoadFileList () [private]
Returns:
true if the file list was successfully loaded from disk
Loads the contents of the file described by mInstallListFilename into mInstalledFiles, mInstalledChecksums, and mInstalledDirectories.
References InstalledFile::Load(), mInstalledDirectories, mInstalledFiles, mInstalledSymLinks, and mInstallListFilename.
Referenced by ConsolidateFiles(), PurgeLegacyFiles(), TransferFilesTo(), and Uninstall().
bool InstallEntry::PurgeLegacyFiles ()
Deletes all non-backup inherited files from disk and removes them from the file list.
Returns:
true if all relevant files were successfully removed
References LoadFileList(), and mInstalledFiles.
void InstallEntry::RemoveReverseDependency (string packageName, string revision, int maxEntries = 1)
Parameters:
packageName - name of the package which depends on this package
revision - revision of the package with depends on this package
maxEntries- the maximum number of matching reverse dependencies to remove
This remove up to maxEntries number of reverse dependencies matching the specified name and revision. There can be 2 matching reverse dependencies in the case where the revision has been installed and an attempt to reinstall has been at least configured.
References mReverseDependencies.
bool InstallEntry::ReverseDependenciesAreInList (const InstallEntryVector & packages) const
Parameters:
packages - list of [partially] installed packages which are possible rerse dependencies of this package
Returns:
false if any of this package's reverse dependencies are not contained in the list of packages
References GetName(), and mReverseDependencies.
bool InstallEntry::ReverseDependencyIsStatic (int depNumber) const
Parameters:
depNumber - the index into the list of reverse dependencies
Returns:
true if it is a static dependency
false if it is not a static dependency or depNumber is invalid
References mReverseDependencies.
Referenced by AppRover::Install().
bool InstallEntry::Save (xmlNodePtr parentNode)
Parameters:
parentNode - the parent DOM node to hold the InstallEntry node
Returns:
false if parentNode is NULL
true otherwise
Saves the install entry data as an XML DOM node that is a child of the specified parent node.
References Revision::GetString(), InstructionSequence::IsEmpty(), IsInstalled(), mBinaryCompatabilityRevision, mDependencies, mErrorMessage, mExcludeFromUpdates, mExplicitInstall, mFeatures, mInstalledDirectories, mInstalledFiles, mInstalledInThisSession, mInstalledSymLinks, mInstallListFilename, mPackageName, mPackageRevision, mPackageSlot, mPackageStatus, mReverseDependencies, mUninstallInstructions, and InstructionSequence::Save().
void InstallEntry::SetBinaryCompatabilityRevision (int revision)
Parameters:
revision - integer used to track whether to revisions have binary compatable interfaces
References mBinaryCompatabilityRevision.
Referenced by AppRover::Install().
void InstallEntry::SetBuilt ()
Flags the log indicating that the package has just completed the build stage.
References mPackageStatus.
Referenced by Package::Build().
void InstallEntry::SetConfigured ()
Flags the log indicating that the package has just completed the configuration stage.
References mPackageStatus.
Referenced by Package::Configure().
void InstallEntry::SetErrorMessage (string errMsg)
Parameters:
errMsg - the error message
Records the error message produced by one of the installation stages
References mErrorMessage.
Referenced by Package::Build(), Package::Configure(), InstructionSequence::Execute(), Package::Fetch(), InstructionSequence::HandleIfStatement(), Package::Install(), InstructionSequence::Translate(), and Package::Unpack().
void InstallEntry::SetExcludeFromUpdates (bool state)
Parameters:
state - true if this package should not be auto-updated
References mExcludeFromUpdates.
void InstallEntry::SetExplicitlyInstalled (bool state)
Parameters:
state - true if this package was installed due to an explicit request from the user
References mExplicitInstall.
Referenced by AppRover::Install().
void InstallEntry::SetInstalled ()
Flags the log indicating that the package has been installed
References mInstalledInThisSession, and mPackageStatus.
Referenced by Package::Install().
void InstallEntry::SetInstallListFilename (string filename)
Parameters:
filename - the file listing the files installed by this package
References mInstallListFilename.
Referenced by AppRover::Install().
void InstallEntry::SetName (string name)
Parameters:
name - name of the package stored in this entry
Records the package name into the install entry.
References mPackageName.
Referenced by AppRover::Install().
void InstallEntry::SetRevision (string revision)
Parameters:
revision - revision of the package stored in this entry
Records the package revision into the install entry.
References mPackageRevision, and Revision::Set().
Referenced by AppRover::Install().
void InstallEntry::SetSlot (string slot)
Parameters:
slot - the slot occupied by this package
References mPackageSlot.
Referenced by AppRover::Install().
void InstallEntry::SetUninstallInstructions (const InstructionSequence & instructions)
Parameters:
instructions - the instructions for uninstalling the package
Records the instructions for removing the package from the system.
References mUninstallInstructions.
Referenced by Package::Install().
void InstallEntry::SetUnpacked ()
Flags the log indicating that the package has just completed the unpacking stage.
References mPackageStatus.
Referenced by Package::Unpack().
bool InstallEntry::TransferFilesTo (InstallEntry * target)
Parameters:
target - the install entry to accept ownership of the files, directories, and symlinks associated with this entry
Returns:
false if target is NULL
Transfers ownership of all files, directories, and symbolic links associated with this entry to the target entry. Since it is expected that these files are about to be overwritten by a new install, any files which have a different md5sum than when they were installed will be backed up to files named .<original name>.arbak
Todo:
Should probably add inherited flag for symlinks and directories
References AddInstalledDirectory(), AddInstalledSymLink(), Interpreter::Interpret(), LoadFileList(), mInstalledDirectories, mInstalledFiles, mInstalledSymLinks, mInstallListFilename, InstalledFile::SetBackup(), InstalledFile::SetChecksum(), and InstalledFile::SetInherited().
Referenced by AppRover::Install().
bool InstallEntry::TransferReverseDependenciesTo (InstallEntry * target)
Parameters:
target - the install entry to accept ownership of the reverse dependencies associated with this entry
Returns:
false if target is NULL
References mReverseDependencies.
Referenced by AppRover::Install().
string InstallEntry::Uninstall (bool backup = true)
Returns:
the error string or "" if successful
Executes the recorded uinstall instructions if they have been specified. Otherwise, removes all files and directories installed by the package. If backup is true (default), any files which have a different md5sum than when they were installed will be backed up to files named .<original name>.arbak
References InstructionSequence::Execute(), Revision::GetString(), Interpreter::Interpret(), InstructionSequence::IsEmpty(), LoadFileList(), mErrorMessage, mInstalledDirectories, mInstalledFiles, mInstalledSymLinks, mInstallListFilename, mPackageName, mPackageRevision, mPackageStatus, mReverseDependencies, and mUninstallInstructions.
Referenced by AppRover::Uninstall().
The documentation for this class was generated from the following files:
InstallEntry.h
InstallEntry.cpp