AppRover: InstructionSequence Class Reference
InstructionSequence Class Reference
Class for managing a series of command line instructions to be executed.
#include <InstructionSequence.h>
Public Member Functions
InstructionSequence (const InstructionSequence &refSequence)
void AddInstruction (string instruction)
void SetStartingDirectory (string directory)
string GetStartingDirectory () const
void SetShell (string shell)
bool Execute (InstallEntry *logEntry, int numProcessors, bool logFilesWritten) const
bool DumpToFile (FILE *file) const
bool Save (xmlNodePtr parentNode, string type) const
bool Load (xmlNodePtr instructionNode)
bool IsEmpty () const
void ReplaceString (string oldString, string newString, bool includeStartingDir)
void Clear ()
InstructionSequence & operator= (const InstructionSequence &src)
Private Member Functions
bool Translate (InstallEntry *logEntry, int numProcessors) const
bool HandleIfStatement (InstallEntry *logEntry, FILE *outputFile, bool skipLines, int &lineNumber) const
bool ConditionFulfilled (const FeatureOptionVector &variables, int lineNumber) const
Private Attributes
vector< string > mInstructions
The list of instructions in this sequence.
string mBaseDirectory
The directory to change to before executing the instructions.
string mShell
The shell used to interpret the instructions.
Detailed Description
Class for managing a series of command line instructions to be executed.
Constructor & Destructor Documentation
InstructionSequence::InstructionSequence (const InstructionSequence & refSequence)
Parameters:
refSequence - instruction sequence to copy
Creates an InstructionSequence object which is an exact copy of refSequence.
References mBaseDirectory, mInstructions, and mShell.
Member Function Documentation
void InstructionSequence::AddInstruction (string instruction)
Parameters:
instruction - an instruction to process
Adds an instruction to the end of the list of instructions.
References mInstructions.
Referenced by Package::AddBuildInstruction(), Package::AddConfigureInstruction(), Package::AddInstallInstruction(), Package::AddUninstallInstruction(), and Package::AddUnpackInstruction().
void InstructionSequence::Clear ()
Deletes all of the stored instructions.
References mInstructions.
Referenced by Package::ClearBuildInstructions(), Package::ClearConfigureInstructions(), Package::ClearInstallInstructions(), Package::ClearUninstallInstructions(), and Package::ClearUnpackInstructions().
bool InstructionSequence::ConditionFulfilled (const FeatureOptionVector & variables, int lineNumber) const [private]
Parameters:
variables - list of optional features and their activation states
lineNumber - the current instruction line to evaluate
Returns:
true if a condition string was successfully parsed and evaluated to true
Todo:
decide how to handle this case
References BooleanExpression::EvaluatesToTrue(), mInstructions, and BooleanExpression::ParseFromString().
Referenced by HandleIfStatement().
bool InstructionSequence::DumpToFile (FILE * file) const
Parameters:
file - the file to receive the contents of these instructions
Returns:
false if the file is NULL
References mInstructions.
Referenced by Package::DumpBuildInstructionsToFile(), Package::DumpConfigureInstructionsToFile(), Package::DumpInstallInstructionsToFile(), Package::DumpUninstallInstructionsToFile(), and Package::DumpUnpackInstructionsToFile().
bool InstructionSequence::Execute (InstallEntry * logEntry, int numProcessors, bool logFilesWritten) const
Parameters:
logEntry - the log entry to receive error messages
numProcessors - number of processors in system (for parallelization)
logFilesWritten - should the names of files written be logged
Returns:
false if an instruction fails
Executes the stored sequence of instructions. If any instruction fails, it immediately returns false. Eventually error messages will be logged.
References Interpreter::Interpret(), mBaseDirectory, InstallEntry::SetErrorMessage(), and Translate().
Referenced by Package::Build(), Package::Configure(), Package::Install(), InstallEntry::Uninstall(), and Package::Unpack().
string InstructionSequence::GetStartingDirectory () const
Returns:
the directory to change to before executing
References mBaseDirectory.
Referenced by Package::Install().
bool InstructionSequence::HandleIfStatement (InstallEntry * logEntry, FILE * outputFile, bool skipLines, int & lineNumber) const [private]
Parameters:
logEntry - the log entry to receive any error messages
outputFile - the script file to receive the translated instructions
skipLines - if true, indicates that we are processing a section of an if statement which will not be executed due to feature conditions
lineNumber - the current line in the list of instructions
Returns:
true if successfully parsed
References ConditionFulfilled(), InstallEntry::GetFeatures(), mInstructions, and InstallEntry::SetErrorMessage().
Referenced by Translate().
bool InstructionSequence::IsEmpty () const
Returns:
true there are no stored instructions
References mInstructions.
Referenced by InstallEntry::Save(), and InstallEntry::Uninstall().
bool InstructionSequence::Load (xmlNodePtr instructionNode)
Parameters:
instructionNode - the xml node which is the parent of the text nodes containing the actual instructions
Returns:
false if parentNode is NULL
Loads the instructions stored as child text nodes of the specified instruction node.
References mInstructions, and SetShell().
Referenced by Package::Load(), and InstallEntry::Load().
InstructionSequence & InstructionSequence::operator= (const InstructionSequence & src)
Parameters:
src - the instruction sequence to be copied
Copies an InstructionSequence
References mBaseDirectory, mInstructions, and mShell.
void InstructionSequence::ReplaceString (string oldString, string newString, bool includeStartingDir)
Deletes all of the stored instructions.
References mBaseDirectory, and mInstructions.
Referenced by Package::Package().
bool InstructionSequence::Save (xmlNodePtr parentNode, string type) const
Parameters:
parentNode - the xml node to serve as the parent of the instruction node
type - string identifying what these instructions are used for
Returns:
false if parentNode is null
Saves the instructions as child nodes of the specified parent node.
References mInstructions, and mShell.
Referenced by Package::Save(), and InstallEntry::Save().
void InstructionSequence::SetShell (string shell)
Parameters:
shell - the shell used to interpret the instructions
References mShell.
Referenced by Load().
void InstructionSequence::SetStartingDirectory (string directory)
Parameters:
directory - the directory to change to before executing
References mBaseDirectory.
Referenced by Package::Build(), Package::Configure(), Package::Install(), and Package::Unpack().
bool InstructionSequence::Translate (InstallEntry * logEntry, int numProcessors) const [private]
Parameters:
logEntry - the log entry to receive any error messages
numProcessors - number of processors in system (for parallelization)
Returns:
true if these instructions were successfully used to create a script file
Todo:
Add support for constants for things like package name
References HandleIfStatement(), Interpreter::Interpret(), mBaseDirectory, mInstructions, mShell, and InstallEntry::SetErrorMessage().
Referenced by Execute().
The documentation for this class was generated from the following files:
InstructionSequence.h
InstructionSequence.cpp