AppRover: PackageDependency Class Reference
PackageDependency Class Reference
Class responsible for representing a dependency between two packages.
#include <PackageDependency.h>
Public Member Functions
PackageDependency (const PackageDependency &clone)
PackageDependency (const PackageDependency &clone, string minRevision, string maxRevision)
PackageDependency (string name, string minRevision, string maxRevision, string type)
bool IsSatisfiedBy (const Package *package) const
bool IsSatisfiedBy (const InstallEntry *package) const
bool IsSatisfiedBy (const string &packageName, const Revision &revision) const
string GetName () const
string GetString () const
string GetType () const
string GetMinRevision () const
string GetMaxRevision () const
bool SetType (string type)
void SetCondition (const BooleanExpression &condition)
string GetDependentString () const
string GetDependentName () const
void SetDependentName (string name)
string GetDependentRevision () const
void SetDependentRevision (string revision)
bool Save (xmlNodePtr parentNode)
bool Load (xmlNodePtr dependencyNode)
bool IsActive (const FeatureOptionVector &features) const
Private Attributes
string mPackageName
The name of the package this dependency refers to.
Revision mMinRevision
The minimum revision of the package which satisfies this dependency.
Revision mMaxRevision
The maximum revision of the package which satisfies this dependency.
BooleanExpression mCondition
The expression of feature conditions which activate this dependency.
string mType
The type of dependency (i.e. install tool, static lib, dynamic lib, etc).
string mDependentName
The name of the package which relies on this dependency (empty unless this is a reverse dependency).
Revision mDependentRevision
The revision of the package which relies on this dependency (meaningless unless this is a reverse dependency).
Detailed Description
Class responsible for representing a dependency between two packages.
Constructor & Destructor Documentation
PackageDependency::PackageDependency (const PackageDependency & clone)
Parameters:
clone - the package dependency to copy
References mCondition, mDependentName, mDependentRevision, mMaxRevision, mMinRevision, mPackageName, and mType.
PackageDependency::PackageDependency (const PackageDependency & clone, string minRevision, string maxRevision)
Parameters:
clone - the package dependency to copy
minRevision - the dependency application's minimum allowed revision
maxRevision - the dependency application's maximum allowed revision
References mCondition, mDependentName, mDependentRevision, mMaxRevision, mMinRevision, mPackageName, mType, and Revision::Set().
PackageDependency::PackageDependency (string name, string minRevision, string maxRevision, string type)
Parameters:
name - the dependency application's name
minRevision - the dependency application's minimum allowed revision
maxRevision - the dependency application's maximum allowed revision
type - the type of dependency ("static", "dynamic", or "install")
References mDependentName, mMaxRevision, mMinRevision, mPackageName, mType, and Revision::Set().
Member Function Documentation
string PackageDependency::GetDependentName () const
Returns:
the name of the package that relies on this dependency
References mDependentName.
string PackageDependency::GetDependentRevision () const
Returns:
the revision of the package that relies on this dependency
References Revision::GetString(), and mDependentRevision.
string PackageDependency::GetDependentString () const
Returns:
human readable string describing the package that relies on this dependency
References BooleanExpression::GetString(), Revision::GetString(), mCondition, mDependentName, and mDependentRevision.
string PackageDependency::GetMaxRevision () const
Returns:
string identifying the maximum required revision
References Revision::GetString(), and mMaxRevision.
Referenced by Package::Package().
string PackageDependency::GetMinRevision () const
Returns:
string identifying the minimum required revision
References Revision::GetString(), and mMinRevision.
Referenced by Package::Package().
string PackageDependency::GetName () const
Returns:
the name of the package required by this dependency
References mPackageName.
Referenced by AppRover::Install(), InstallLog::RegisterReverseDependency(), and InstallLog::Satisfies().
string PackageDependency::GetString () const
Returns:
human readable string describing this dependency
References Revision::GetString(), BooleanExpression::GetString(), Revision::IsSet(), mCondition, mMaxRevision, mMinRevision, and mPackageName.
Referenced by AppRover::Install().
string PackageDependency::GetType () const
Returns:
string describing the dependency relationship ("static", "dynamic", or "install")
References mType.
Referenced by InstallLog::RegisterReverseDependency().
bool PackageDependency::IsActive (const FeatureOptionVector & features) const
Parameters:
features - the set of features used to evaluate the dependency condition
Returns:
true if the dependency condition is empty or evaluates to true (which indicates that this dependency cannot be ignored)
References BooleanExpression::EvaluatesToTrue(), BooleanExpression::IsEmpty(), and mCondition.
Referenced by AppRover::Install().
bool PackageDependency::IsSatisfiedBy (const InstallEntry * package) const
Parameters:
package - an installed package which potentially satisfies the dependency
Returns:
false if package is NULL or does not satisfy the dependency
Determines whether the specified package satisfies this dependency.
Todo:
Add support for blocking dependencies
Todo:
Add support for "virtual" dependencies
References InstallEntry::GetName(), InstallEntry::GetRevision(), Revision::IsSet(), mMaxRevision, mMinRevision, and mPackageName.
bool PackageDependency::IsSatisfiedBy (const Package * package) const
Parameters:
package - a package which potentially satisfies the dependency
Returns:
false if package is NULL or does not satisfy the dependency
Determines whether the specified package satisfies this dependency.
Todo:
Add support for blocking dependencies
Todo:
Add support for "virtual" dependencies
References Package::GetName(), Package::GetRevision(), Revision::IsSet(), mMaxRevision, mMinRevision, and mPackageName.
Referenced by AppRover::FindMostCurrentPackage(), PackageIndex::GetMostCurrentPackage(), InstallLog::RegisterReverseDependency(), and InstallLog::Satisfies().
bool PackageDependency::IsSatisfiedBy (const string & packageName, const Revision & revision) const
Parameters:
packageName - name of a package which potentially satisfies the dependency
revision - revision of a package which potentially satisfies the dependency
Returns:
false if package name and revision does not satisfy the dependency
Determines whether the specified package satisfies this dependency.
Todo:
Add support for blocking dependencies
Todo:
Add support for "virtual" dependencies
References Revision::IsSet(), mMaxRevision, mMinRevision, and mPackageName.
bool PackageDependency::Load (xmlNodePtr dependencyNode)
Parameters:
dependencyNode - the XML DOM node containing the dependency data
Returns:
false if dependencyNode is NULL or there is a format error
Loads the dependency data from the specified node.
References mCondition, mDependentName, mDependentRevision, mMaxRevision, mMinRevision, mPackageName, mType, BooleanExpression::ParseFromString(), and Revision::Set().
Referenced by Package::Load(), and InstallEntry::Load().
bool PackageDependency::Save (xmlNodePtr parentNode)
Parameters:
parentNode - the parent XML DOM node for the dependency node
Returns:
false if parentNode is NULL
Saves the dependency data as a child node of the specified parent.
References BooleanExpression::GetString(), Revision::GetString(), Revision::IsSet(), mCondition, mDependentName, mDependentRevision, mMaxRevision, mMinRevision, mPackageName, and mType.
void PackageDependency::SetCondition (const BooleanExpression & condition)
Parameters:
condition - the boolean expresssion which activates this dependency
References mCondition.
void PackageDependency::SetDependentName (string name)
Parameters:
name - the name of the package that relies on this dependency
References mDependentName.
Referenced by InstallEntry::AddReverseDependency().
void PackageDependency::SetDependentRevision (string revision)
Parameters:
revision - the revision of the package that relies on this dependency
References mDependentRevision, and Revision::Set().
Referenced by InstallEntry::AddReverseDependency().
bool PackageDependency::SetType (string type)
Parameters:
type - the dependency relationship ("static", "dynamic", or "install")
Returns:
true if type is valid
References mType.
The documentation for this class was generated from the following files:
PackageDependency.h
PackageDependency.cpp