AppRover: ActionDescriptionVector Class Reference
ActionDescriptionVector Class Reference
Vector class for ActionDescriptions which prevents duplicate entries.
#include <ActionDescription.h>
Inherits std::vector< ActionDescription * >.
Public Member Functions
void push_back (ActionDescription *element)
Detailed Description
Vector class for ActionDescriptions which prevents duplicate entries.
Member Function Documentation
void ActionDescriptionVector::push_back (ActionDescription * element)
Parameters:
element - the action description to add to the vector
Adds the element to the end of the vector. If the element matches an element that is already in the vector, the new element is simply deleted.
Referenced by AppRover::Clean(), AppRover::Install(), and AppRover::Uninstall().
The documentation for this class was generated from the following files:
ActionDescription.h
ActionDescription.cpp