AppRover: ConfigMgr Class Reference
ConfigMgr Class Reference
Class responsible for managing all system specific AppRover configuration details.
#include <ConfigMgr.h>
Public Member Functions
ConfigMgrStatusType Load (string filename)
ConfigMgrStatusType Save (string filename)
ConfigMgrStatusType Save ()
string GetInstallLogFilename () const
int GetNumRepositories () const
string GetRepositoryDirectory (int repositoryNumber) const
bool AddRepositoryDirectory (string directory)
string GetStorageDirectory () const
void SetStorageDirectory (string directory)
string GetWorkDirectory () const
void SetWorkDirectory (string directory)
string GetInstallFileDirectory () const
void SetInstallFileDirectory (string directory)
int GetNumProcessors ()
int GetFeatureState (string featureName)
void SetFeatureState (string featureName, int state)
Private Member Functions
void DetectNumProcessors ()
Determines the number of processors in the system and sets mNumProcessors accordingly.
Private Attributes
vector< string > mRepositoryDirectories
List of the location of all repositories in this system.
string mInstallLogFilename
Name of the file containing the install log.
string mStorageDirectory
The directory where are fetched files are stored.
string mWorkDirectory
The top level directory where all file operations are performed prior to installing a package.
string mInstallFileDirectory
The directory containing the lists of files installed by packages.
string mCfgFilename
The file where this configuration data is stored.
int mNumProcessors
The number processing cores in the system.
map< string, bool > mFeatureSettings
The system wide default values for a set of optional features.
Detailed Description
Class responsible for managing all system specific AppRover configuration details.
Member Function Documentation
bool ConfigMgr::AddRepositoryDirectory (string directory)
Parameters:
directory - the full path of the directory containing the repository
Returns:
false if directory is "" or already has been specified
Adds add repository directory to the configuration. This only records a location - nothing is actually done to the repository.
References mRepositoryDirectories.
Referenced by AppRover::AddNewRepository().
int ConfigMgr::GetFeatureState (string featureName)
Parameters:
featureName - name of the optional feature whose activation status is desired
Returns:
FEATURE_ENABLED if the feature has been activated
FEATURE_DISABLE if the feature has been deactivated
FEATURE_USE_DEFAULT if a system default value has not been set (indicates that the package specific default should be used)
References mFeatureSettings.
Referenced by AppRover::Install().
string ConfigMgr::GetInstallFileDirectory () const
Returns:
the directory where lists of installed files are stored
References mInstallFileDirectory.
Referenced by AppRover::Install().
string ConfigMgr::GetInstallLogFilename () const
Returns:
the name of the file containing the installation log
References mInstallLogFilename.
Referenced by AppRover::AppRover(), AppRover::BuildPackage(), AppRover::Clean(), AppRover::ConfigurePackage(), AppRover::ExcludeFromUpdates(), AppRover::FetchPackage(), AppRover::Install(), AppRover::InstallPackage(), AppRover::Purify(), AppRover::Uninstall(), and AppRover::UnpackPackage().
int ConfigMgr::GetNumProcessors ()
Returns:
number of processors in system (0 if unknown)
References mNumProcessors.
Referenced by AppRover::BuildPackage(), AppRover::ConfigurePackage(), AppRover::InstallPackage(), and AppRover::UnpackPackage().
int ConfigMgr::GetNumRepositories () const
Returns:
the number of repositories specified in the configuration
References mRepositoryDirectories.
Referenced by AppRover::AppRover(), and AppRover::SynchronizeRepositories().
string ConfigMgr::GetRepositoryDirectory (int repositoryNumber) const
Parameters:
repositoryNumber - the index for the list of repositories
Returns:
the full path of the directory containing the repository ("" if repositoryNumber is invalid)
References mRepositoryDirectories.
Referenced by AppRover::AppRover(), and AppRover::SynchronizeRepositories().
string ConfigMgr::GetStorageDirectory () const
Returns:
the directory used for storing fetched files
References mStorageDirectory.
Referenced by AppRover::AddNewPackage(), AppRover::FetchPackage(), AppRover::UnpackPackage(), and AppRover::UpdatePackageChecksums().
string ConfigMgr::GetWorkDirectory () const
Returns:
the full path to the directory which houses individual package working directories
References mWorkDirectory.
Referenced by AppRover::BuildPackage(), AppRover::Clean(), AppRover::ConfigurePackage(), AppRover::Install(), AppRover::InstallPackage(), and AppRover::UnpackPackage().
ConfigMgrStatusType ConfigMgr::Load (string filename)
Returns:
CFG_FILE_NOT_SPECIFIED if a filename has never been specified
CFG_FILE_MISSING if the file does not exist
CFG_FILE_FORMAT_ERROR if there is a problem with the file data
CFG_OK if successful
Loads the configuration of the ConfigMgr from file.
References DetectNumProcessors(), mCfgFilename, mFeatureSettings, mInstallFileDirectory, mInstallLogFilename, mNumProcessors, mRepositoryDirectories, mStorageDirectory, and mWorkDirectory.
Referenced by AppRover::AppRover().
ConfigMgrStatusType ConfigMgr::Save (string filename)
Parameters:
filename - the name of the configuration file
Returns:
CFG_FILE_NOT_SPECIFIED if filename is ""
CFG_FILE_NOT_WRITABLE if the file cannot be opened for writing
CFG_OK if successful
Saves the configuration of the ConfigMgr to file.
References DetectNumProcessors(), mCfgFilename, mFeatureSettings, mInstallFileDirectory, mInstallLogFilename, mNumProcessors, mRepositoryDirectories, mStorageDirectory, and mWorkDirectory.
Referenced by AppRover::ActivateFeature(), AppRover::AddNewRepository(), and AppRover::AppRover().
ConfigMgrStatusType ConfigMgr::Save ()
Returns:
CFG_FILE_NOT_SPECIFIED if a filename has never been specified
CFG_FILE_NOT_WRITABLE if the file cannot be opened for writing
CFG_OK if successful
Saves the configuration of the ConfigMgr to file which was last used for either saving or loading.
References mCfgFilename.
void ConfigMgr::SetFeatureState (string featureName, int state)
Parameters:
featureName - the name of optional feature whose system default should be set
state - the system default state for the feature
References mFeatureSettings.
Referenced by AppRover::ActivateFeature().
void ConfigMgr::SetInstallFileDirectory (string directory)
Parameters:
directory - name of the directory where lists of installed fiels should be stored
References mInstallFileDirectory.
void ConfigMgr::SetStorageDirectory (string directory)
Parameters:
directory - the full path of the storage directory
Changes the location of the storage directory. The old directory remains untouched, but is no longer used. If the new directory does not exist, it is created.
References mStorageDirectory.
void ConfigMgr::SetWorkDirectory (string directory)
Parameters:
directory - the full path of the work directory
Changes the location of the work directory. The old directory remains untouched, but is no longer used. If the new directory does not exist, it is created.
References mWorkDirectory.
The documentation for this class was generated from the following files:
ConfigMgr.h
ConfigMgr.cpp