AppRover: AppRover Class Reference
AppRover Class Reference
The main workhorse of the AppRover library.
#include <AppRover.h>
Public Member Functions
AppRover (string cfgFilename)
string Update (bool pretend, ActionDescriptionVector &actionList)
string ExcludeFromUpdates (string packageName, bool state)
string Purify (string packageName)
string Install (string packageName, string revisionStr, bool pretend, ActionDescriptionVector &actionList, AppRoverHaltStageType haltStage=STAGE_INSTALL, bool allowReinstall=false, bool explicitInstall=true)
string Uninstall (string packageName, bool pretend, ActionDescriptionVector &actionList)
string Clean (bool pretend, ActionDescriptionVector &actionList, bool keepPartials=false)
bool AddNewRepository (string baseLocation)
bool AddNewPackage (Package *newPackage, int repositoryNumber=0)
void UpdatePackageChecksums (Package *package)
Package * GetPackage (string packageName, string revision, int repositoryNumber=0)
Package * GetPrecedingPackage (string packageName, string revision, int repositoryNumber=0)
Package * GetPackage (string packageName, int repositoryNumber=0)
int NumPackages ()
string GetPackageName (int packageIndex)
string GetInstalledRevisionNumber (int packageIndex)
vector< string > ActivateFeature (string featureName, bool activationState)
void ActivateFeatureForPackage (string packageName, string featureName, bool activationState)
string SynchronizeRepositories ()
Private Member Functions
Package * FindMostCurrentPackage (string packageName, const PackageDependency *dependency=NULL)
Package * FindPackage (string packageName, string revisionStr)
bool FetchPackage (const Package *package, InstallEntry *logEntry, bool force=false)
bool UnpackPackage (Package *package, InstallEntry *logEntry)
bool ConfigurePackage (Package *package, InstallEntry *logEntry)
bool BuildPackage (Package *package, InstallEntry *logEntry)
bool InstallPackage (Package *package, InstallEntry *logEntry)
void PopulatePackageList ()
Private Attributes
ConfigMgr mConfig
the configuration manager for the system
RepositoryVector mRepositories
the package repositories that are present in this system
InstallLog mInstallLog
the log of all applications that have been [partially] installed
vector< string > mPackageList
the list of names of packages available from all of the repositories
vector< string > mRevisionList
the list of revisions of packages available from all of the repositories
bool mPackageListIsInvalid
indiciates whether the name and revision lists need to be updated
Detailed Description
The main workhorse of the AppRover library.
Constructor & Destructor Documentation
AppRover::AppRover (string cfgFilename)
Parameters:
cfgFilename - File containing the AppRover XML configuration data
References ConfigMgr::GetInstallLogFilename(), ConfigMgr::GetNumRepositories(), ConfigMgr::GetRepositoryDirectory(), Repository::Load(), InstallLog::Load(), ConfigMgr::Load(), mConfig, mInstallLog, mPackageListIsInvalid, mRepositories, PopulatePackageList(), Repository::Save(), InstallLog::Save(), and ConfigMgr::Save().
Member Function Documentation
vector< string > AppRover::ActivateFeature (string featureName, bool activationState)
Parameters:
featureName - the name of the optional feature to activate
activationState - the state to which the feature should be set (true to activate, false to deactivate)
Returns:
the names of the installed packages which may use the optional feature
Sets the default state for whether the specified optional feature should be activated for a clean install of a package. Packages which are already installed are not affected.
References InstallLog::GetPackagesUsingFeature(), mConfig, mInstallLog, ConfigMgr::Save(), and ConfigMgr::SetFeatureState().
void AppRover::ActivateFeatureForPackage (string packageName, string featureName, bool activationState)
Todo:
this function should be removed and activated feature should be passed as an argument to Install
References InstallLog::GetPackagesUsingFeature(), and mInstallLog.
bool AppRover::AddNewPackage (Package * newPackage, int repositoryNumber = 0)
Parameters:
newPackage - the package to insert into the repository
repositoryNumber - the index of the repository to receive the package
Returns:
false if null package, invalid repositoryNumber or package is a duplicate of another in the repository
Adds a package into the specified repository
References ConfigMgr::GetStorageDirectory(), mConfig, mPackageListIsInvalid, mRepositories, PopulatePackageList(), and Package::RecordSourceChecksums().
Referenced by AppRoverKWindow::CreateNewPackage().
bool AppRover::AddNewRepository (string baseLocation)
Parameters:
baseLocation - The directory containing the repository.cfg file
Returns:
false if directory is not specified, is not writable, or the repository already exists
Creates an empty repository in the specified directory.
References ConfigMgr::AddRepositoryDirectory(), mConfig, mRepositories, ConfigMgr::Save(), Repository::Save(), and Repository::SetDirectory().
bool AppRover::BuildPackage (Package * package, InstallEntry * logEntry) [private]
Parameters:
package - the package to build
logEntry - the entry in the install log corresponding to the package
Returns:
- false if there is a failure
Configures the package if needed. Processes any package specific building instructions and executes them from the package's working directory. This should only be needed for source-based packages.
References Package::Build(), ConfigurePackage(), ConfigMgr::GetInstallLogFilename(), ConfigMgr::GetNumProcessors(), ConfigMgr::GetWorkDirectory(), InstallEntry::IsAtLeastConfigured(), mConfig, mInstallLog, and InstallLog::Save().
Referenced by Install(), and InstallPackage().
string AppRover::Clean (bool pretend, ActionDescriptionVector & actionList, bool keepPartials = false)
Parameters:
pretend - If true, generates a list of actions to be performed
actionList - List which receives the actions if operating in pretend mode
keepPartials - If true, partially installed packages are unaffected
Returns:
string containing any error message
Removes all partially installed packages and uninstalls packages which are no longer needed (i.e. not explicity installed and is not a dependency of an explicity installed package).
References InstallLog::DeleteEntry(), ConfigMgr::GetInstallLogFilename(), InstallLog::GetPartiallyInstalledPackages(), InstallLog::GetUnneededPackages(), ConfigMgr::GetWorkDirectory(), Interpreter::Interpret(), mConfig, mInstallLog, PopulatePackageList(), ActionDescriptionVector::push_back(), InstallLog::Save(), ActionDescription::SetAction(), ActionDescription::SetOldRevision(), and ActionDescription::SetPackageName().
bool AppRover::ConfigurePackage (Package * package, InstallEntry * logEntry) [private]
Parameters:
package - the package to configure
logEntry - the entry in the install log corresponding to the package
Returns:
false if there is a failure
Unpacks the package if needed. Processes any package specific configuration instructions and executes them from the package's working directory. This should only be needed for source-based packages. In most cases where this is used, the instructions will call ./configure with correct options.
References Package::Configure(), ConfigMgr::GetInstallLogFilename(), ConfigMgr::GetNumProcessors(), ConfigMgr::GetWorkDirectory(), InstallEntry::IsAtLeastUnpacked(), mConfig, mInstallLog, InstallLog::Save(), and UnpackPackage().
Referenced by BuildPackage(), and Install().
string AppRover::ExcludeFromUpdates (string packageName, bool state)
Parameters:
packageName name of package
state true to exclude, false to include
Returns:
error message
Flags whether the specified package should or should not be processed by the Update function.
References InstallLog::GetInstalledEntries(), ConfigMgr::GetInstallLogFilename(), mConfig, mInstallLog, and InstallLog::Save().
bool AppRover::FetchPackage (const Package * package, InstallEntry * logEntry, bool force = false) [private]
Parameters:
package - the package to fetch
logEntry - the entry in the install log corresponding to the package
force - if true, fetch all files even if a local copy exists
Returns:
false if there is a failure in fetching the files
Downloads all files needed to install the package and places them in the storage directory. If force is false, only the files which are not already stored locally will be downloaded.
References Package::Fetch(), ConfigMgr::GetInstallLogFilename(), ConfigMgr::GetStorageDirectory(), mConfig, mInstallLog, and InstallLog::Save().
Referenced by Install(), and UnpackPackage().
Package * AppRover::FindMostCurrentPackage (string packageName, const PackageDependency * dependency = NULL) [private]
Parameters:
packageName - the name of the package
dependency - the dependency requirements
Returns:
The package with the highest revision or the package with the highest revision which satisfies the dependency
Locates the most current revision of the package with the specified name. If dependency is non-null, it locates the most current revision which statisfies the dependency.
References Package::IsNewerThan(), PackageDependency::IsSatisfiedBy(), and mRepositories.
Referenced by Install().
Package * AppRover::FindPackage (string packageName, string revisionStr) [private]
Parameters:
packageName - the name of the package
revisionStr - the desired revision of the package
Returns:
The package specified name and revision
References mRepositories.
Referenced by Install().
string AppRover::GetInstalledRevisionNumber (int packageIndex)
Parameters:
packageIndex - the index into the list of package names
Returns:
string containing the revision number that has been installed for the specified package ("" if invalid index or package has not been installed)
References mRevisionList.
Referenced by AppRoverKWindow::FillOutPackageList(), and Update().
Package * AppRover::GetPackage (string packageName, string revision, int repositoryNumber = 0)
Parameters:
packageName - the name of the application whose package should be retrieved
revision - the revision of the application handled by the package
repositoryNumber - the index representing the repository from which the package should be retrieved.
References mRepositories.
Package * AppRover::GetPackage (string packageName, int repositoryNumber = 0)
Parameters:
packageName - the name of the application whose latest package should be retrieved
repositoryNumber - the index representing the repository from which the package should be retrieved.
References mRepositories.
string AppRover::GetPackageName (int packageIndex)
Parameters:
packageIndex - the index into the list of package names
Returns:
"" if invalid index, otherwise the name of an available package
References mPackageList.
Referenced by AppRoverKWindow::FillOutPackageList(), PopulatePackageList(), and Update().
Package * AppRover::GetPrecedingPackage (string packageName, string revision, int repositoryNumber = 0)
Parameters:
packageName - the name of the application whose package should be retrieved
revision - the upper bound revision of the application handled by the package
repositoryNumber - the index representing the repository from which the package should be retrieved.
References mRepositories.
string AppRover::Install (string packageName, string revisionStr, bool pretend, ActionDescriptionVector & actionList, AppRoverHaltStageType haltStage = STAGE_INSTALL, bool allowReinstall = false, bool explicitInstall = true)
Parameters:
packageName - The name of the package to install
pretend - if true, only generate a list of actions that would be performed
actionList - List to receive the actions if operating in pretend mode
haltStage - The last stage of the installation process which should be executed
allowReinstall - If true, the package should be installed even if it has already been installed
explicitInstall - If true, the user has explicitly requested the package to be installed, otherwise it is assumed to be a dependency of another package
Todo:
This does a minimal update. Need to make an option to do a full update or a full reinstall
References InstallEntry::AddDependency(), InstallLog::AddEntry(), InstallEntry::AddFeature(), BuildPackage(), InstallEntry::ClearDependencies(), ConfigurePackage(), InstallLog::DeleteEntry(), FeatureOption::Disable(), FeatureOption::Enable(), FetchPackage(), InstallLog::FindEntry(), InstallLog::FindInstalledSlotOccupant(), FindMostCurrentPackage(), FindPackage(), InstallLog::FindPartiallyInstalledEntry(), ActionDescription::GetAction(), InstallEntry::GetBinaryCompatabilityRevision(), Package::GetBinaryCompatabilityRevision(), Package::GetDependency(), InstallEntry::GetErrorMessage(), Package::GetFeature(), InstallEntry::GetFeatures(), ConfigMgr::GetFeatureState(), InstallEntry::GetFeatureState(), ConfigMgr::GetInstallFileDirectory(), ConfigMgr::GetInstallLogFilename(), PackageDependency::GetName(), FeatureOption::GetName(), Package::GetName(), Package::GetNumDependencies(), Package::GetNumFeatures(), InstallEntry::GetNumReverseDependencies(), InstallEntry::GetReverseDependencyName(), InstallEntry::GetRevision(), Package::GetRevision(), Package::GetSlot(), PackageDependency::GetString(), Revision::GetString(), ConfigMgr::GetWorkDirectory(), InstallEntry::HasFeature(), InstallPackage(), PackageDependency::IsActive(), InstallEntry::IsAtLeastConfigured(), InstallEntry::IsAtLeastUnpacked(), InstallEntry::IsBuilt(), InstallEntry::IsExplicitlyInstalled(), InstallEntry::IsInstalled(), mConfig, mInstallLog, PopulatePackageList(), ActionDescriptionVector::push_back(), InstallLog::RegisterReverseDependency(), InstallLog::RemovePartiallyInstalledSlotMates(), InstallEntry::ReverseDependencyIsStatic(), InstallLog::Satisfies(), InstallLog::Save(), ActionDescription::SetAction(), InstallEntry::SetBinaryCompatabilityRevision(), ActionDescription::SetError(), InstallEntry::SetExplicitlyInstalled(), ActionDescription::SetFeatures(), InstallEntry::SetInstallListFilename(), InstallEntry::SetName(), ActionDescription::SetNewRevision(), ActionDescription::SetOldRevision(), ActionDescription::SetPackageName(), InstallEntry::SetRevision(), InstallEntry::SetSlot(), InstallEntry::TransferFilesTo(), InstallEntry::TransferReverseDependenciesTo(), and UnpackPackage().
Referenced by AppRoverKWindow::Install(), Purify(), and Update().
bool AppRover::InstallPackage (Package * package, InstallEntry * logEntry) [private]
Parameters:
package - the package to build
logEntry - the entry in the install log corresponding to the package
Returns:
false if there is a failure
Builds the package if needed. Processes any package specific building instructions and executes them from the package's working directory.
References BuildPackage(), ConfigMgr::GetInstallLogFilename(), ConfigMgr::GetNumProcessors(), ConfigMgr::GetWorkDirectory(), Package::Install(), InstallEntry::IsBuilt(), mConfig, mInstallLog, and InstallLog::Save().
Referenced by Install().
int AppRover::NumPackages ()
Returns:
The number of unique package names in all combined repositories
References mPackageList.
Referenced by AppRoverKWindow::FillOutPackageList(), and Update().
void AppRover::PopulatePackageList () [private]
Generates a consolidated list of packages and revisions for use with the functions GetNumPackages, GetPackageName, and GetInstalledRevisionNumber.
Todo:
Sort the list and make sure there are no duplicate entries
References GetPackageName(), InstallLog::GetRevisionInstalled(), mInstallLog, mPackageList, mPackageListIsInvalid, mRepositories, and mRevisionList.
Referenced by AddNewPackage(), AppRover(), Clean(), Install(), and Uninstall().
string AppRover::Purify (string packageName)
Parameters:
packageName name of package
Returns:
error message
Removes leftover files and rebuilds the package in order to purge remnants of older installed versions of the package.
References InstallLog::GetInstalledEntries(), ConfigMgr::GetInstallLogFilename(), Install(), mConfig, mInstallLog, and InstallLog::Save().
string AppRover::SynchronizeRepositories ()
Returns:
string containing any error message
Updates all repositories to match their sources (not applicable for local repositories).
References Repository::GetDirectory(), ConfigMgr::GetNumRepositories(), ConfigMgr::GetRepositoryDirectory(), Repository::Load(), mConfig, mRepositories, and Repository::Save().
string AppRover::Uninstall (string packageName, bool pretend, ActionDescriptionVector & actionList)
Parameters:
packageName - The name of the package to update
pretend - If true, generates a list of actions which would be performed
actionList - List which receives the actions if operating in pretend mode
Returns:
string containing an error message ("" if successful)
Uninstalls all versions of the specified package.
Todo:
May want to add a means to protect some versions
References InstallLog::DeleteEntry(), InstallLog::FindNextOldestInstalledEntry(), InstallLog::FindOldestInstalledEntry(), ConfigMgr::GetInstallLogFilename(), InstallEntry::GetRevision(), Revision::GetString(), mConfig, mInstallLog, PopulatePackageList(), ActionDescriptionVector::push_back(), InstallLog::Save(), ActionDescription::SetAction(), ActionDescription::SetOldRevision(), ActionDescription::SetPackageName(), and InstallEntry::Uninstall().
Referenced by AppRoverKWindow::Uninstall().
bool AppRover::UnpackPackage (Package * package, InstallEntry * logEntry) [private]
Parameters:
package - the package to unpack
logEntry - the entry in the install log corresponding to the package
Returns:
false if there is a failure
Fetches the package if needed. Creates a working directory for the package and copies all of the needed files from the storage directory to the working directory. If the package contains any specific unpacking instructions (like untarring, uncompressing, or patching files) they are then executed in the working directory.
References FetchPackage(), ConfigMgr::GetInstallLogFilename(), ConfigMgr::GetNumProcessors(), ConfigMgr::GetStorageDirectory(), ConfigMgr::GetWorkDirectory(), mConfig, mInstallLog, InstallLog::Save(), and Package::Unpack().
Referenced by ConfigurePackage(), and Install().
string AppRover::Update (bool pretend, ActionDescriptionVector & actionList)
Parameters:
pretend - if true, only generate a list of actions that would be performed
actionList - List to receive the actions if operating in pretend mode
Returns:
error message
Installs the latest version of each of the installed packages. If a package is already at the latest revisiion, it is NOT rebuilt.
References InstallLog::FindEntry(), GetInstalledRevisionNumber(), GetPackageName(), Package::GetRevision(), Revision::GetString(), Install(), InstallEntry::IsExcludedFromUpdates(), InstallEntry::IsExplicitlyInstalled(), mInstallLog, and NumPackages().
void AppRover::UpdatePackageChecksums (Package * package)
Parameters:
package - the package whose source file checksums need to be updated
Recalculates and records the checksums for all files which are required to install the package
References ConfigMgr::GetStorageDirectory(), mConfig, and Package::RecordSourceChecksums().
The documentation for this class was generated from the following files:
AppRover.h
AppRover.cpp