AppRover: Fetcher Class Reference
Fetcher Class Reference
The class which handles all downloads of required files.
#include <Fetcher.h>
Public Member Functions
bool Fetch (string fileLocation, string storageDirectory, string checksum="", bool force=false) const
string GetChecksum (string fileLocation, string storageDirectory) const
Detailed Description
The class which handles all downloads of required files.
Member Function Documentation
bool Fetcher::Fetch (string fileLocation, string storageDirectory, string checksum = "", bool force = false) const
Parameters:
fileLocation - the remote location of the file
storageDirectory - the directory to hold the local copy of the file
checksum - string to check md5sum against, check disabled if ""
force - if true, the file will be fetched even if a local copy exists
Returns:
false if file cannot be downloaded or the file exists and cannot be forcibly removed
true if successful or fle already exists
Downloads the file from the specifed location and stores it in the storage directory. If the file is already in the storage directory, it will only be downloaded if force is true.
References GetChecksum(), and Interpreter::Interpret().
Referenced by Package::Fetch(), Package::RecordSourceChecksums(), and Repository::Synchronize().
string Fetcher::GetChecksum (string fileLocation, string storageDirectory) const
Parameters:
fileLocation - the remove location of the file
storageDirectory - the directory where the file is locally stored
Returns:
the checksum for the local copy of the specified file
Referenced by Fetch(), and Package::RecordSourceChecksums().
The documentation for this class was generated from the following files:
Fetcher.h
Fetcher.cpp